-- Update airport descriptions 
-- (use Code to avoid ID differences in different environments)
UPDATE Airport SET [Description]='Hartford, CT' WHERE Code='BDL'
UPDATE Airport SET [Description]='Billings, MT' WHERE Code='BIL'
UPDATE Airport SET [Description]='Baltimore, MD' WHERE Code='BPN'
UPDATE Airport SET [Description]='Boston, MA' WHERE Code='BSS'
UPDATE Airport SET [Description]='Baltimore, MD' WHERE Code='BWI'
UPDATE Airport SET [Description]='Sault Sainte Marie, MI' WHERE Code='CUI'
UPDATE Airport SET [Description]='Mosinee, WI' WHERE Code='CWA'
UPDATE Airport SET [Description]='Dallas, TX' WHERE Code='DAL'
UPDATE Airport SET [Description]='Washington, DC' WHERE Code='DCA'
UPDATE Airport SET [Description]='Dallas, TX' WHERE Code='DFW'
UPDATE Airport SET [Description]='Kearney, NE' WHERE Code='EAR'
UPDATE Airport SET [Description]='Grand Island, NE' WHERE Code='GRI'
UPDATE Airport SET [Description]='Houston, TX' WHERE Code='HOU'
UPDATE Airport SET [Description]='Washington, DC' WHERE Code='IAD'
UPDATE Airport SET [Description]='Houston, TX' WHERE Code='IAH'
UPDATE Airport SET [Description]='Kingston, RI' WHERE Code='KIN'
UPDATE Airport SET [Description]='Harrisburg, PA' WHERE Code='MDT'
UPDATE Airport SET [Description]='Chicago, IL' WHERE Code='MDW'
UPDATE Airport SET [Description]='Chicago, IL' WHERE Code='ORD'
UPDATE Airport SET [Description]='San Juan, PR' WHERE Code='SJU'
UPDATE Airport SET [Description]='Washington, DC' WHERE Code='WUN'