INSERT INTO UserAccountRecovery ([UserId]
           ,[RecoveryQuestionId]
           ,[Answer]
           ,[QuestionOrder]
           ,[ModifiedBy]
           ,[ModifiedDate])
SELECT [ViewUser].UserID, CASE WHEN SYS_USER_SECURITY_QUESTION.SECURITY_QUESTION_ID = 1 THEN 16 
	WHEN SYS_USER_SECURITY_QUESTION.SECURITY_QUESTION_ID = 2 THEN 8 
	WHEN SYS_USER_SECURITY_QUESTION.SECURITY_QUESTION_ID = 3 THEN 17 ELSE 18 END,
	CONVERT(VARCHAR(40), HASHBYTES('SHA1', UPPER(LTRIM(RTRIM(CAST(SYS_USER_SECURITY_QUESTION.ANSWER AS VARCHAR(100)))))), 2), Val.Val,
	VUN.UserId, SYS_USER_SECURITY_QUESTION.LAST_UPDATE_DATE
FROM [$(P2RMIS)].dbo.SYS_USER_SECURITY_QUESTION SYS_USER_SECURITY_QUESTION INNER JOIN
	[$(P2RMIS)].dbo.SYS_Users SYS_Users ON SYS_USER_SECURITY_QUESTION.UserID = SYS_Users.UserID INNER JOIN
	[ViewUser] ON SYS_Users.Person_ID = ViewUser.PersonID LEFT OUTER JOIN
	[ViewLegacyUserNameToUserId] VUN ON SYS_USER_SECURITY_QUESTION.LAST_UPDATED_BY = VUN.UserName CROSS JOIN
	(SELECT 1 AS Val UNION ALL SELECT 2 UNION ALL SELECT 3) AS Val 
WHERE NOT EXISTS (Select 'X' FROM UserAccountRecovery WHERE UserAccountRecovery.UserId = ViewUser.UserID)

	


