//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLogReason
    {
        public ActionLogReason()
        {
            this.ActionLogs = new HashSet<ActionLog>();
        }
    
        public int ActionLogReasonId { get; set; }
        public string Reason { get; set; }
    
        public virtual ICollection<ActionLog> ActionLogs { get; set; }
    }
}
