//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationSummaryLog
    {
        public int ApplicationSummaryLogId { get; set; }
        public Nullable<int> ApplicationWorkflowStepId { get; set; }
        public int UserId { get; set; }
        public bool CompletedFlag { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ApplicationWorkflowStep ApplicationWorkflowStep { get; set; }
        public virtual User User { get; set; }
    }
}
