//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationWorkflowStepElement
    {
        public ApplicationWorkflowStepElement()
        {
            this.ApplicationWorkflowStepElementComments = new HashSet<ApplicationWorkflowStepElementComment>();
            this.ApplicationWorkflowStepElementContents = new HashSet<ApplicationWorkflowStepElementContent>();
        }
    
        public int ApplicationWorkflowStepElementId { get; set; }
        public int ApplicationWorkflowStepId { get; set; }
        public int ApplicationTemplateElementId { get; set; }
        public int AccessLevelId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ClientScoringId { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual AccessLevel AccessLevel { get; set; }
        public virtual ApplicationTemplateElement ApplicationTemplateElement { get; set; }
        public virtual ApplicationWorkflowStep ApplicationWorkflowStep { get; set; }
        public virtual ICollection<ApplicationWorkflowStepElementComment> ApplicationWorkflowStepElementComments { get; set; }
        public virtual ICollection<ApplicationWorkflowStepElementContent> ApplicationWorkflowStepElementContents { get; set; }
        public virtual ClientScoringScale ClientScoringScale { get; set; }
    }
}
