//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationWorkflowStepElementContentHistory
    {
        public int ApplicationWorkflowStepElementContenHistorytId { get; set; }
        public int ApplicationWorkflowStepElementId { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string ContentText { get; set; }
        public bool Abstain { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ApplicationWorkflowStepWorkLog1 { get; set; }
    
        public virtual ApplicationWorkflowStepWorkLog ApplicationWorkflowStepWorkLog11 { get; set; }
    }
}
