//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationStage
    {
        public ApplicationStage()
        {
            this.ApplicationTemplates = new HashSet<ApplicationTemplate>();
            this.ApplicationWorkflows = new HashSet<ApplicationWorkflow>();
            this.ApplicationStageSteps = new HashSet<ApplicationStageStep>();
        }
    
        public int ApplicationStageId { get; set; }
        public int PanelApplicationId { get; set; }
        public int ReviewStageId { get; set; }
        public int StageOrder { get; set; }
        public bool ActiveFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool AssignmentVisibilityFlag { get; set; }
        public Nullable<System.DateTime> AssignmentReleaseDate { get; set; }
    
        public virtual PanelApplication PanelApplication { get; set; }
        public virtual ReviewStage ReviewStage { get; set; }
        public virtual ICollection<ApplicationTemplate> ApplicationTemplates { get; set; }
        public virtual ICollection<ApplicationWorkflow> ApplicationWorkflows { get; set; }
        public virtual ICollection<ApplicationStageStep> ApplicationStageSteps { get; set; }
    }
}
