//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationWorkflow
    {
        public ApplicationWorkflow()
        {
            this.ApplicationWorkflowSteps = new HashSet<ApplicationWorkflowStep>();
            this.ApplicationWorkflowSummaryStatements = new HashSet<ApplicationWorkflowSummaryStatement>();
        }
    
        public int ApplicationWorkflowId { get; set; }
        public int WorkflowId { get; set; }
        public int ApplicationTemplateId { get; set; }
        public string ApplicationWorkflowName { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ApplicationStageId { get; set; }
        public Nullable<int> PanelUserAssignmentId { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ApplicationTemplate ApplicationTemplate { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual ICollection<ApplicationWorkflowStep> ApplicationWorkflowSteps { get; set; }
        public virtual ApplicationStage ApplicationStage { get; set; }
        public virtual PanelUserAssignment PanelUserAssignment { get; set; }
        public virtual ICollection<ApplicationWorkflowSummaryStatement> ApplicationWorkflowSummaryStatements { get; set; }
    }
}
