//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationWorkflowStepElementComment
    {
        public int ApplicationWorkflowStepElementCommentId { get; set; }
        public int ApplicationWorkflowStepElementId { get; set; }
        public int UserId { get; set; }
        public string Comment { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ApplicationWorkflowStepElement ApplicationWorkflowStepElement { get; set; }
        public virtual User User { get; set; }
    }
}
