//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationWorkflowStep
    {
        public ApplicationWorkflowStep()
        {
            this.ApplicationWorkflowStepElements = new HashSet<ApplicationWorkflowStepElement>();
            this.ApplicationWorkflowStepAssignments = new HashSet<ApplicationWorkflowStepAssignment>();
            this.ApplicationWorkflowStepWorkLogs = new HashSet<ApplicationWorkflowStepWorkLog>();
            this.ApplicationSummaryLogs = new HashSet<ApplicationSummaryLog>();
        }
    
        public int ApplicationWorkflowStepId { get; set; }
        public int ApplicationWorkflowId { get; set; }
        public int StepTypeId { get; set; }
        public string StepName { get; set; }
        public bool Active { get; set; }
        public int StepOrder { get; set; }
        public bool Resolution { get; set; }
        public Nullable<System.DateTime> ResolutionDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ApplicationWorkflow ApplicationWorkflow { get; set; }
        public virtual StepType StepType { get; set; }
        public virtual ICollection<ApplicationWorkflowStepElement> ApplicationWorkflowStepElements { get; set; }
        public virtual ICollection<ApplicationWorkflowStepAssignment> ApplicationWorkflowStepAssignments { get; set; }
        public virtual ICollection<ApplicationWorkflowStepWorkLog> ApplicationWorkflowStepWorkLogs { get; set; }
        public virtual ICollection<ApplicationSummaryLog> ApplicationSummaryLogs { get; set; }
    }
}
