//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationTemplate
    {
        public ApplicationTemplate()
        {
            this.ApplicationTemplateElements = new HashSet<ApplicationTemplateElement>();
            this.ApplicationWorkflows = new HashSet<ApplicationWorkflow>();
        }
    
        public int ApplicationTemplateId { get; set; }
        public int ApplicationId { get; set; }
        public int MechanismTemplateId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ApplicationStageId { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual MechanismTemplate MechanismTemplate { get; set; }
        public virtual ICollection<ApplicationTemplateElement> ApplicationTemplateElements { get; set; }
        public virtual ICollection<ApplicationWorkflow> ApplicationWorkflows { get; set; }
        public virtual ApplicationStage ApplicationStage { get; set; }
    }
}
