//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationWorkflowStepWorkLog
    {
        public ApplicationWorkflowStepWorkLog()
        {
            this.ApplicationWorkflowStepElementContentHistories1 = new HashSet<ApplicationWorkflowStepElementContentHistory>();
        }
    
        public int ApplicationWorkflowStepWorkLogId { get; set; }
        public int ApplicationWorkflowStepId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public byte[] CheckoutBackupFile { get; set; }
        public byte[] CheckinBackupFile { get; set; }
        public Nullable<int> CheckInUserId { get; set; }
    
        public virtual ApplicationWorkflowStep ApplicationWorkflowStep { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ApplicationWorkflowStepElementContentHistory> ApplicationWorkflowStepElementContentHistories1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
