//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationBudget
    {
        public int ApplicationBudgetId { get; set; }
        public int ApplicationId { get; set; }
        public Nullable<decimal> DirectCosts { get; set; }
        public Nullable<decimal> IndirectCosts { get; set; }
        public Nullable<decimal> TotalFunding { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> CommentModifiedBy { get; set; }
        public Nullable<System.DateTime> CommentModifiedDate { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
