//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.ApplicationTemplates = new HashSet<ApplicationTemplate>();
            this.ApplicationDefaultWorkflows = new HashSet<ApplicationDefaultWorkflow>();
            this.ApplicationBudgets = new HashSet<ApplicationBudget>();
            this.ApplicationInfoes = new HashSet<ApplicationInfo>();
            this.ApplicationPersonnels = new HashSet<ApplicationPersonnel>();
            this.ApplicationTexts = new HashSet<ApplicationText>();
            this.PanelApplications = new HashSet<PanelApplication>();
            this.Application1 = new HashSet<Application>();
            this.ApplicationResearchCategories = new HashSet<ApplicationResearchCategory>();
            this.ApplicationCompliances = new HashSet<ApplicationCompliance>();
            this.ReferralMappingDatas = new HashSet<ReferralMappingData>();
            this.ApplicationTopicCodes = new HashSet<ApplicationTopicCode>();
        }
    
        public int ApplicationId { get; set; }
        public string LogNumber { get; set; }
        public int ProgramMechanismId { get; set; }
        public string ApplicationTitle { get; set; }
        public string ResearchArea { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ParentApplicationId { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
        public Nullable<System.DateTime> ProjectEndDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool WithdrawnFlag { get; set; }
        public Nullable<int> WithdrawnBy { get; set; }
        public Nullable<System.DateTime> WithdrawnDate { get; set; }
    
        public virtual ICollection<ApplicationTemplate> ApplicationTemplates { get; set; }
        public virtual ICollection<ApplicationDefaultWorkflow> ApplicationDefaultWorkflows { get; set; }
        public virtual ProgramMechanism ProgramMechanism { get; set; }
        public virtual ICollection<ApplicationBudget> ApplicationBudgets { get; set; }
        public virtual ICollection<ApplicationInfo> ApplicationInfoes { get; set; }
        public virtual ICollection<ApplicationPersonnel> ApplicationPersonnels { get; set; }
        public virtual ICollection<ApplicationText> ApplicationTexts { get; set; }
        public virtual ICollection<PanelApplication> PanelApplications { get; set; }
        public virtual ICollection<Application> Application1 { get; set; }
        public virtual Application Application2 { get; set; }
        public virtual ICollection<ApplicationResearchCategory> ApplicationResearchCategories { get; set; }
        public virtual ICollection<ApplicationCompliance> ApplicationCompliances { get; set; }
        public virtual ICollection<ReferralMappingData> ReferralMappingDatas { get; set; }
        public virtual ICollection<ApplicationTopicCode> ApplicationTopicCodes { get; set; }
    }
}
