//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentTypeThreshold
    {
        public int AssignmentTypeThresholdId { get; set; }
        public Nullable<int> ScientistReviewerSortOrder { get; set; }
        public Nullable<int> AdvocateConsumerSortOrder { get; set; }
        public int SessionPanelId { get; set; }
        public Nullable<int> SpecialistReviewerSortOrder { get; set; }
    
        public virtual SessionPanel SessionPanel { get; set; }
    }
}
