//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCoiType
    {
        public ClientCoiType()
        {
            this.PanelApplicationReviewerCoiDetails = new HashSet<PanelApplicationReviewerCoiDetail>();
        }
    
        public int ClientCoiTypeId { get; set; }
        public int ClientId { get; set; }
        public string CoiTypeName { get; set; }
        public string CoiTypeDescription { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<PanelApplicationReviewerCoiDetail> PanelApplicationReviewerCoiDetails { get; set; }
    }
}
