//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRegistrationDocumentItem
    {
        public int ClientRegistrationDocumentItemId { get; set; }
        public int ClientRegistrationDocumentId { get; set; }
        public int RegistrationDocumentItemId { get; set; }
        public bool RequiredFlag { get; set; }
        public string RequiredMessage { get; set; }
    
        public virtual ClientRegistrationDocument ClientRegistrationDocument { get; set; }
        public virtual RegistrationDocumentItem RegistrationDocumentItem { get; set; }
    }
}
