//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRole
    {
        public ClientRole()
        {
            this.PanelUserAssignments = new HashSet<PanelUserAssignment>();
            this.SummaryReviewerDescriptions = new HashSet<SummaryReviewerDescription>();
            this.PanelUserPotentialAssignments = new HashSet<PanelUserPotentialAssignment>();
        }
    
        public int ClientRoleId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> LegacyRoleId { get; set; }
        public string RoleAbbreviation { get; set; }
        public string RoleName { get; set; }
        public bool ActiveFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool SpecialistFlag { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<PanelUserAssignment> PanelUserAssignments { get; set; }
        public virtual ICollection<SummaryReviewerDescription> SummaryReviewerDescriptions { get; set; }
        public virtual ICollection<PanelUserPotentialAssignment> PanelUserPotentialAssignments { get; set; }
    }
}
