//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.UserClients = new HashSet<UserClient>();
            this.Workflows = new HashSet<Workflow>();
            this.ClientElements = new HashSet<ClientElement>();
            this.ClientScoringScales = new HashSet<ClientScoringScale>();
            this.ClientAwardTypes = new HashSet<ClientAwardType>();
            this.ClientMeetings = new HashSet<ClientMeeting>();
            this.ClientParticipantTypes = new HashSet<ClientParticipantType>();
            this.ClientPrograms1 = new HashSet<ClientProgram>();
            this.ClientRoles = new HashSet<ClientRole>();
            this.ClientApplicationPersonnelTypes = new HashSet<ClientApplicationPersonnelType>();
            this.ClientApplicationTextTypes = new HashSet<ClientApplicationTextType>();
            this.ClientCoiTypes = new HashSet<ClientCoiType>();
            this.ClientExpertiseRatings = new HashSet<ClientExpertiseRating>();
            this.ClientAssignmentTypes = new HashSet<ClientAssignmentType>();
            this.ClientReviewerEvaluationGroups = new HashSet<ClientReviewerEvaluationGroup>();
            this.ClientRegistrations = new HashSet<ClientRegistration>();
            this.ClientConfigurations = new HashSet<ClientConfiguration>();
            this.ScoringTemplates = new HashSet<ScoringTemplate>();
            this.RoleParticipantTypes = new HashSet<RoleParticipantType>();
            this.ClientDataDeliverables = new HashSet<ClientDataDeliverable>();
            this.ClientServiceAccounts = new HashSet<ClientServiceAccount>();
            this.ClientTransferTypes = new HashSet<ClientTransferType>();
            this.PeerReviewDocuments = new HashSet<PeerReviewDocument>();
            this.UserBlockLogClients = new HashSet<UserBlockLogClient>();
            this.UserClientBlocks = new HashSet<UserClientBlock>();
            this.ClientDefaultWorkflows = new HashSet<ClientDefaultWorkflow>();
            this.ClientFileConfigurations = new HashSet<ClientFileConfiguration>();
            this.ClientSummaryTemplates = new HashSet<ClientSummaryTemplate>();
            this.Policies = new HashSet<Policy>();
        }
    
        public int ClientID { get; set; }
        public string ClientAbrv { get; set; }
        public string ClientDesc { get; set; }
        public int SummaryStatementModeId { get; set; }
    
        public virtual ICollection<UserClient> UserClients { get; set; }
        public virtual ICollection<Workflow> Workflows { get; set; }
        public virtual ICollection<ClientElement> ClientElements { get; set; }
        public virtual ICollection<ClientScoringScale> ClientScoringScales { get; set; }
        public virtual ICollection<ClientAwardType> ClientAwardTypes { get; set; }
        public virtual ICollection<ClientMeeting> ClientMeetings { get; set; }
        public virtual ICollection<ClientParticipantType> ClientParticipantTypes { get; set; }
        public virtual ICollection<ClientProgram> ClientPrograms1 { get; set; }
        public virtual ICollection<ClientRole> ClientRoles { get; set; }
        public virtual ICollection<ClientApplicationPersonnelType> ClientApplicationPersonnelTypes { get; set; }
        public virtual ICollection<ClientApplicationTextType> ClientApplicationTextTypes { get; set; }
        public virtual ICollection<ClientCoiType> ClientCoiTypes { get; set; }
        public virtual ICollection<ClientExpertiseRating> ClientExpertiseRatings { get; set; }
        public virtual ICollection<ClientAssignmentType> ClientAssignmentTypes { get; set; }
        public virtual ICollection<ClientReviewerEvaluationGroup> ClientReviewerEvaluationGroups { get; set; }
        public virtual ICollection<ClientRegistration> ClientRegistrations { get; set; }
        public virtual ICollection<ClientConfiguration> ClientConfigurations { get; set; }
        public virtual ICollection<ScoringTemplate> ScoringTemplates { get; set; }
        public virtual SummaryStatementMode SummaryStatementMode { get; set; }
        public virtual ICollection<RoleParticipantType> RoleParticipantTypes { get; set; }
        public virtual ICollection<ClientDataDeliverable> ClientDataDeliverables { get; set; }
        public virtual ICollection<ClientServiceAccount> ClientServiceAccounts { get; set; }
        public virtual ICollection<ClientTransferType> ClientTransferTypes { get; set; }
        public virtual ICollection<PeerReviewDocument> PeerReviewDocuments { get; set; }
        public virtual ICollection<UserBlockLogClient> UserBlockLogClients { get; set; }
        public virtual ICollection<UserClientBlock> UserClientBlocks { get; set; }
        public virtual ICollection<ClientDefaultWorkflow> ClientDefaultWorkflows { get; set; }
        public virtual ICollection<ClientFileConfiguration> ClientFileConfigurations { get; set; }
        public virtual ICollection<ClientSummaryTemplate> ClientSummaryTemplates { get; set; }
        public virtual ICollection<Policy> Policies { get; set; }
    }
}
