//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProgram
    {
        public ClientProgram()
        {
            this.ProgramPanels = new HashSet<ProgramPanel>();
            this.ProgramYears = new HashSet<ProgramYear>();
            this.PeerReviewDocuments = new HashSet<PeerReviewDocument>();
        }
    
        public int ClientProgramId { get; set; }
        public string LegacyProgramId { get; set; }
        public int ClientId { get; set; }
        public string ProgramAbbreviation { get; set; }
        public string ProgramDescription { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ProgramPanel> ProgramPanels { get; set; }
        public virtual ICollection<ProgramYear> ProgramYears { get; set; }
        public virtual ICollection<PeerReviewDocument> PeerReviewDocuments { get; set; }
    }
}
