//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSummaryTemplate
    {
        public ClientSummaryTemplate()
        {
            this.ProgramMechanismSummaryStatements = new HashSet<ProgramMechanismSummaryStatement>();
        }
    
        public int ClientSummaryTemplateId { get; set; }
        public int ClientId { get; set; }
        public string TemplateName { get; set; }
        public string TemplateFileName { get; set; }
        public string StoredProcedureName { get; set; }
        public bool ActiveFlag { get; set; }
        public string PreviewLinkUrl { get; set; }
        public bool ExpeditedFlag { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ProgramMechanismSummaryStatement> ProgramMechanismSummaryStatements { get; set; }
    }
}
