//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientTransferType
    {
        public ClientTransferType()
        {
            this.ImportLogs = new HashSet<ImportLog>();
        }
    
        public int ClientTransferTypeId { get; set; }
        public int ClientId { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public string ApiPath { get; set; }
        public string ExternalUrl { get; set; }
        public string ExternalUrlParameters { get; set; }
        public string AuthenticationType { get; set; }
        public string ReturnFormat { get; set; }
        public string Credentials { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ImportLog> ImportLogs { get; set; }
    }
}
