//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientElement
    {
        public ClientElement()
        {
            this.MechanismTemplateElements = new HashSet<MechanismTemplateElement>();
        }
    
        public int ClientElementId { get; set; }
        public int ClientId { get; set; }
        public string ElementIdentifier { get; set; }
        public string ElementAbbreviation { get; set; }
        public string ElementDescription { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ElementTypeId { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<MechanismTemplateElement> MechanismTemplateElements { get; set; }
        public virtual ElementType ElementType { get; set; }
    }
}
