//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRegistrationDocument
    {
        public ClientRegistrationDocument()
        {
            this.PanelUserRegistrationDocuments = new HashSet<PanelUserRegistrationDocument>();
            this.ClientRegistrationDocumentItems = new HashSet<ClientRegistrationDocumentItem>();
        }
    
        public int ClientRegistrationDocumentId { get; set; }
        public int ClientRegistrationId { get; set; }
        public string DocumentName { get; set; }
        public int SortOrder { get; set; }
        public string DocumentRoute { get; set; }
        public bool RequiredFlag { get; set; }
        public int DocumentVersion { get; set; }
        public System.DateTime DocumentUpdateDate { get; set; }
        public string ConfirmationText { get; set; }
        public int RegistrationDocumentTypeId { get; set; }
        public string ReportFileName { get; set; }
        public string DocumentAbbreviation { get; set; }
    
        public virtual ClientRegistration ClientRegistration { get; set; }
        public virtual ICollection<PanelUserRegistrationDocument> PanelUserRegistrationDocuments { get; set; }
        public virtual ICollection<ClientRegistrationDocumentItem> ClientRegistrationDocumentItems { get; set; }
        public virtual RegistrationDocumentType RegistrationDocumentType { get; set; }
    }
}
