//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientScoringScaleLegend
    {
        public ClientScoringScaleLegend()
        {
            this.ClientScoringScales = new HashSet<ClientScoringScale>();
            this.ClientScoringScaleLegendItems = new HashSet<ClientScoringScaleLegendItem>();
        }
    
        public int ClientScoringScaleLegendId { get; set; }
        public int ClientId { get; set; }
        public string LegendName { get; set; }
    
        public virtual ICollection<ClientScoringScale> ClientScoringScales { get; set; }
        public virtual ICollection<ClientScoringScaleLegendItem> ClientScoringScaleLegendItems { get; set; }
    }
}
