//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAssignmentType
    {
        public ClientAssignmentType()
        {
            this.PanelApplicationReviewerAssignments = new HashSet<PanelApplicationReviewerAssignment>();
        }
    
        public int ClientAssignmentTypeId { get; set; }
        public int ClientId { get; set; }
        public int AssignmentTypeId { get; set; }
        public string AssignmentAbbreviation { get; set; }
        public string AssignmentLabel { get; set; }
    
        public virtual AssignmentType AssignmentType { get; set; }
        public virtual Client Client { get; set; }
        public virtual ICollection<PanelApplicationReviewerAssignment> PanelApplicationReviewerAssignments { get; set; }
    }
}
