//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientExpertiseRating
    {
        public ClientExpertiseRating()
        {
            this.PanelApplicationReviewerExpertises = new HashSet<PanelApplicationReviewerExpertise>();
        }
    
        public int ClientExpertiseRatingId { get; set; }
        public int ClientId { get; set; }
        public string RatingAbbreviation { get; set; }
        public string RatingName { get; set; }
        public string RatingDescription { get; set; }
        public bool ConflictFlag { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<PanelApplicationReviewerExpertise> PanelApplicationReviewerExpertises { get; set; }
    }
}
