//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientScoringScaleLegendItem
    {
        public int ClientScoringScaleLegendItemId { get; set; }
        public int ClientScoringScaleLegendId { get; set; }
        public string LegendItemLabel { get; set; }
        public string HighValueLabel { get; set; }
        public string LowValueLabel { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ClientScoringScaleLegend ClientScoringScaleLegend { get; set; }
    }
}
