//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientScoringScale
    {
        public ClientScoringScale()
        {
            this.ClientScoringScaleAdjectivals = new HashSet<ClientScoringScaleAdjectival>();
            this.ApplicationWorkflowStepElements = new HashSet<ApplicationWorkflowStepElement>();
            this.MechanismTemplateElementScorings = new HashSet<MechanismTemplateElementScoring>();
            this.ScoringTemplatePhases = new HashSet<ScoringTemplatePhase>();
            this.ScoringTemplatePhases1 = new HashSet<ScoringTemplatePhase>();
        }
    
        public int ClientScoringId { get; set; }
        public int ClientId { get; set; }
        public string ScoreType { get; set; }
        public decimal HighValue { get; set; }
        public string HighValueDescription { get; set; }
        public Nullable<decimal> MiddleValue { get; set; }
        public string MiddleValueDescription { get; set; }
        public decimal LowValue { get; set; }
        public string LowValueDescription { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ClientScoringScaleLegendId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ClientScoringScaleAdjectival> ClientScoringScaleAdjectivals { get; set; }
        public virtual ICollection<ApplicationWorkflowStepElement> ApplicationWorkflowStepElements { get; set; }
        public virtual ICollection<MechanismTemplateElementScoring> MechanismTemplateElementScorings { get; set; }
        public virtual ClientScoringScaleLegend ClientScoringScaleLegend { get; set; }
        public virtual ICollection<ScoringTemplatePhase> ScoringTemplatePhases { get; set; }
        public virtual ICollection<ScoringTemplatePhase> ScoringTemplatePhases1 { get; set; }
    }
}
