//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMeeting
    {
        public ClientMeeting()
        {
            this.MeetingSessions = new HashSet<MeetingSession>();
            this.ProgramMeetings = new HashSet<ProgramMeeting>();
        }
    
        public int ClientMeetingId { get; set; }
        public string LegacyMeetingId { get; set; }
        public int ClientId { get; set; }
        public string MeetingAbbreviation { get; set; }
        public string MeetingDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string MeetingLocation { get; set; }
        public int MeetingTypeId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> HotelId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual MeetingType MeetingType { get; set; }
        public virtual ICollection<MeetingSession> MeetingSessions { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<ProgramMeeting> ProgramMeetings { get; set; }
    }
}
