//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRegistration
    {
        public ClientRegistration()
        {
            this.ClientRegistrationDocuments = new HashSet<ClientRegistrationDocument>();
            this.PanelUserRegistrations = new HashSet<PanelUserRegistration>();
        }
    
        public int ClientRegistrationId { get; set; }
        public int ClientId { get; set; }
        public bool ActiveFlag { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ClientRegistrationDocument> ClientRegistrationDocuments { get; set; }
        public virtual ICollection<PanelUserRegistration> PanelUserRegistrations { get; set; }
    }
}
