//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAwardType
    {
        public ClientAwardType()
        {
            this.ProgramMechanism = new HashSet<ProgramMechanism>();
            this.ClientAwardType1 = new HashSet<ClientAwardType>();
        }
    
        public int ClientAwardTypeId { get; set; }
        public int ClientId { get; set; }
        public string LegacyAwardTypeId { get; set; }
        public string AwardAbbreviation { get; set; }
        public string AwardDescription { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ParentAwardTypeId { get; set; }
        public Nullable<int> MechanismRelationshipTypeId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ProgramMechanism> ProgramMechanism { get; set; }
        public virtual ICollection<ClientAwardType> ClientAwardType1 { get; set; }
        public virtual ClientAwardType ClientAwardType2 { get; set; }
        public virtual MechanismRelationshipType MechanismRelationshipType { get; set; }
    }
}
