//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicationLog
    {
        public CommunicationLog()
        {
            this.CommunicationLogAttachments = new HashSet<CommunicationLogAttachment>();
            this.CommunicationLogRecipients = new HashSet<CommunicationLogRecipient>();
        }
    
        public int CommunicationLogId { get; set; }
        public int SessionPanelId { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string BCC { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual SessionPanel SessionPanel { get; set; }
        public virtual ICollection<CommunicationLogAttachment> CommunicationLogAttachments { get; set; }
        public virtual ICollection<CommunicationLogRecipient> CommunicationLogRecipients { get; set; }
    }
}
