//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplianceStatu
    {
        public ComplianceStatu()
        {
            this.ApplicationCompliances = new HashSet<ApplicationCompliance>();
        }
    
        public int ComplianceStatusId { get; set; }
        public string ComplianceStatusLabel { get; set; }
    
        public virtual ICollection<ApplicationCompliance> ApplicationCompliances { get; set; }
    }
}
