//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class Competition
    {
        public Competition()
        {
            this.CompTopicGoals = new HashSet<CompTopicGoal>();
        }
    
        public int CompetitionID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string CFDA { get; set; }
        public string CompetitionName { get; set; }
        public Nullable<System.DateTime> AppStartDate { get; set; }
        public Nullable<System.DateTime> AppDeadline { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<bool> LOIActive { get; set; }
        public Nullable<int> CompMng { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CompTopicGoal> CompTopicGoals { get; set; }
    }
    
}
