//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class CompTopicGoal
    {
        public int CompTopicGoalID { get; set; }
        public Nullable<int> CompetitionID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<int> GoalID { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual LookupGoal LookupGoal { get; set; }
        public virtual LookupTopic LookupTopic { get; set; }
    }
    
}
