//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractStatus
    {
        public ContractStatus()
        {
            this.PanelUserRegistrationDocumentContracts = new HashSet<PanelUserRegistrationDocumentContract>();
        }
    
        public int ContractStatusId { get; set; }
        public string StatusLabel { get; set; }
        public int SortOrder { get; set; }
        public string ActionLabel { get; set; }
        public bool UserActionFlag { get; set; }
    
        public virtual ICollection<PanelUserRegistrationDocumentContract> PanelUserRegistrationDocumentContracts { get; set; }
    }
}
