//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementType
    {
        public ElementType()
        {
            this.ClientElements = new HashSet<ClientElement>();
        }
    
        public int ElementTypeId { get; set; }
        public string ElementTypeName { get; set; }
    
        public virtual ICollection<ClientElement> ClientElements { get; set; }
    }
}
