//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStore
    {
        public int FileID { get; set; }
        public System.Guid FileStoreID { get; set; }
        public string FileStoreContent { get; set; }
        public string FileStoreName { get; set; }
        public string FileContentType { get; set; }
        public Nullable<long> FileStoreSize { get; set; }
        public string FileStoreExt { get; set; }
        public string FileAuthor { get; set; }
        public string FileComment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int VersionNumber { get; set; }
        public int FileStoreMainId { get; set; }
    
        public virtual FileStoreMain FileStoreMain { get; set; }
    }
}
