//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStoreMain
    {
        public FileStoreMain()
        {
            this.FileStores = new HashSet<FileStore>();
        }
    
        public int FileStoreMainId { get; set; }
        public System.Guid rowguid { get; set; }
        public int ActiveVersion { get; set; }
    
        public virtual ICollection<FileStore> FileStores { get; set; }
    }
}
