//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupStage
    {
        public LookupStage()
        {
            this.Users = new HashSet<User>();
            this.UserAddresses = new HashSet<UserAddress>();
        }
    
        public int StageID { get; set; }
        public string StageName { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
    }
}
