//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupUSState
    {
        public LookupUSState()
        {
            this.UserAddresses = new HashSet<UserAddress>();
        }
    
        public int USStateID { get; set; }
        public string USStateName { get; set; }
        public string USStateFullName { get; set; }
    
        public virtual LookupUSState LookupUSState1 { get; set; }
        public virtual LookupUSState LookupUSState2 { get; set; }
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
    }
}
