//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupRole
    {
        public LookupRole()
        {
            this.UserSystemRoles = new HashSet<UserSystemRole>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleContext { get; set; }
        public string RoleCode { get; set; }
        public Nullable<int> PriorityOrder { get; set; }
    
        public virtual ICollection<UserSystemRole> UserSystemRoles { get; set; }
    }
}
