//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupTemplateStage
    {
        public LookupTemplateStage()
        {
            this.SystemTemplateVersions = new HashSet<SystemTemplateVersion>();
        }
    
        public int TemplateStageID { get; set; }
        public string TemplateStageName { get; set; }
    
        public virtual ICollection<SystemTemplateVersion> SystemTemplateVersions { get; set; }
    }
}
