//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MechanismRelationshipType
    {
        public MechanismRelationshipType()
        {
            this.ClientAwardTypes = new HashSet<ClientAwardType>();
        }
    
        public int MechanismRelationshipTypeId { get; set; }
        public string RelationshipType { get; set; }
    
        public virtual ICollection<ClientAwardType> ClientAwardTypes { get; set; }
    }
}
