//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MechanismTemplate
    {
        public MechanismTemplate()
        {
            this.ApplicationTemplates = new HashSet<ApplicationTemplate>();
            this.MechanismTemplateElements = new HashSet<MechanismTemplateElement>();
        }
    
        public int MechanismTemplateId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ReviewStatusId { get; set; }
        public int ProgramMechanismId { get; set; }
        public int ReviewStageId { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> SummaryDocumentId { get; set; }
    
        public virtual ICollection<ApplicationTemplate> ApplicationTemplates { get; set; }
        public virtual ICollection<MechanismTemplateElement> MechanismTemplateElements { get; set; }
        public virtual ReviewStatu ReviewStatu { get; set; }
        public virtual ProgramMechanism ProgramMechanism { get; set; }
        public virtual ReviewStage ReviewStage { get; set; }
        public virtual SummaryDocument SummaryDocument { get; set; }
    }
}
