//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MechanismTemplateElement
    {
        public MechanismTemplateElement()
        {
            this.ApplicationTemplateElements = new HashSet<ApplicationTemplateElement>();
            this.MechanismTemplateElementScorings = new HashSet<MechanismTemplateElementScoring>();
        }
    
        public int MechanismTemplateElementId { get; set; }
        public int MechanismTemplateId { get; set; }
        public int ClientElementId { get; set; }
        public string InstructionText { get; set; }
        public int SortOrder { get; set; }
        public Nullable<int> RecommendedWordCount { get; set; }
        public bool ScoreFlag { get; set; }
        public bool TextFlag { get; set; }
        public bool OverallFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> LegacyEcmId { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool ShowAbbreviationOnScoreboard { get; set; }
        public Nullable<int> SummarySortOrder { get; set; }
        public bool SummaryIncludeFlag { get; set; }
    
        public virtual ICollection<ApplicationTemplateElement> ApplicationTemplateElements { get; set; }
        public virtual ClientElement ClientElement { get; set; }
        public virtual MechanismTemplate MechanismTemplate { get; set; }
        public virtual ICollection<MechanismTemplateElementScoring> MechanismTemplateElementScorings { get; set; }
    }
}
