//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingRegistrationTravelFlight
    {
        public int MeetingRegistrationTravelFlightId { get; set; }
        public int MeetingRegistrationTravelId { get; set; }
        public string CarrierName { get; set; }
        public string FlightNumber { get; set; }
        public string DepartureCity { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string ArrivalCity { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual MeetingRegistrationTravel MeetingRegistrationTravel { get; set; }
        public virtual User ModifiedByUser { get; set; }
    }
}
