//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingRegistrationTravel
    {
        public MeetingRegistrationTravel()
        {
            this.MeetingRegistrationTravelFlights = new HashSet<MeetingRegistrationTravelFlight>();
        }
    
        public int MeetingRegistrationTravelId { get; set; }
        public int MeetingRegistrationId { get; set; }
        public Nullable<int> TravelModeId { get; set; }
        public string TravelRequestComments { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> LegacyTravelId { get; set; }
        public Nullable<decimal> NteAmount { get; set; }
        public bool CancellationFlag { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public string ReservationCode { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public Nullable<decimal> AgentFee { get; set; }
        public Nullable<decimal> ChangeFee { get; set; }
        public bool Ground { get; set; }
        public Nullable<decimal> GsaRate { get; set; }
        public bool NoGsa { get; set; }
        public Nullable<decimal> ClientApprovedAmount { get; set; }
        public Nullable<decimal> AgentFee2 { get; set; }
        public bool IsDataComplete { get; set; }
    
        public virtual MeetingRegistration MeetingRegistration { get; set; }
        public virtual TravelMode TravelMode { get; set; }
        public virtual ICollection<MeetingRegistrationTravelFlight> MeetingRegistrationTravelFlights { get; set; }
    }
}
