//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingRegistration
    {
        public MeetingRegistration()
        {
            this.MeetingRegistrationAttendances = new HashSet<MeetingRegistrationAttendance>();
            this.MeetingRegistrationHotels = new HashSet<MeetingRegistrationHotel>();
            this.MeetingRegistrationTravels = new HashSet<MeetingRegistrationTravel>();
            this.MeetingRegistrationComments = new HashSet<MeetingRegistrationComment>();
        }
    
        public int MeetingRegistrationId { get; set; }
        public Nullable<int> PanelUserAssignmentId { get; set; }
        public bool RegistrationSubmittedFlag { get; set; }
        public Nullable<System.DateTime> RegistrationSubmittedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> LegacyMrId { get; set; }
        public Nullable<int> SessionUserAssignmentId { get; set; }
    
        public virtual PanelUserAssignment PanelUserAssignment { get; set; }
        public virtual ICollection<MeetingRegistrationAttendance> MeetingRegistrationAttendances { get; set; }
        public virtual ICollection<MeetingRegistrationHotel> MeetingRegistrationHotels { get; set; }
        public virtual ICollection<MeetingRegistrationTravel> MeetingRegistrationTravels { get; set; }
        public virtual ICollection<MeetingRegistrationComment> MeetingRegistrationComments { get; set; }
        public virtual SessionUserAssignment SessionUserAssignment { get; set; }
    }
}
