//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingType
    {
        public MeetingType()
        {
            this.ClientMeetings = new HashSet<ClientMeeting>();
            this.ProgramSessionPayRates = new HashSet<ProgramSessionPayRate>();
        }
    
        public int MeetingTypeId { get; set; }
        public string LegacyMeetingTypeId { get; set; }
        public string MeetingTypeAbbreviation { get; set; }
        public string MeetingTypeName { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<ClientMeeting> ClientMeetings { get; set; }
        public virtual ICollection<ProgramSessionPayRate> ProgramSessionPayRates { get; set; }
    }
}
