//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingRegistrationHotel
    {
        public int MeetingRegistrationHotelId { get; set; }
        public int MeetingRegistrationId { get; set; }
        public Nullable<System.DateTime> HotelCheckInDate { get; set; }
        public Nullable<System.DateTime> HotelCheckOutDate { get; set; }
        public bool HotelDoubleOccupancy { get; set; }
        public string ExtraNightsRequestComments { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> LegacyHousingId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public bool CancellationFlag { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public string HotelAndFoodRequestComments { get; set; }
        public Nullable<System.DateTime> ParticipantModifiedDate { get; set; }
        public bool IsDataComplete { get; set; }
        public bool HotelNotRequiredFlag { get; set; }
    
        public virtual MeetingRegistration MeetingRegistration { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
