//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingSession
    {
        public MeetingSession()
        {
            this.SessionPanels = new HashSet<SessionPanel>();
            this.SessionPhases = new HashSet<SessionPhase>();
            this.SessionUserAssignments = new HashSet<SessionUserAssignment>();
            this.ProgramSessionPayRates = new HashSet<ProgramSessionPayRate>();
        }
    
        public int MeetingSessionId { get; set; }
        public string LegacySessionId { get; set; }
        public int ClientMeetingId { get; set; }
        public string SessionAbbreviation { get; set; }
        public string SessionDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ClientMeeting ClientMeeting { get; set; }
        public virtual ICollection<SessionPanel> SessionPanels { get; set; }
        public virtual ICollection<SessionPhase> SessionPhases { get; set; }
        public virtual ICollection<SessionUserAssignment> SessionUserAssignments { get; set; }
        public virtual ICollection<ProgramSessionPayRate> ProgramSessionPayRates { get; set; }
    }
}
