//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomineeProgram
    {
        public int NomineeProgramid { get; set; }
        public int NomineeId { get; set; }
        public Nullable<int> LegacyNomineeId { get; set; }
        public Nullable<int> NomineeSponsorId { get; set; }
        public Nullable<int> ProgramYearId { get; set; }
        public Nullable<int> NomineeTypeId { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> NomineeAffectedId { get; set; }
        public bool PrimaryFlag { get; set; }
        public string DiseaseSite { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Nominee Nominee { get; set; }
        public virtual NomineeAffected NomineeAffected { get; set; }
        public virtual NomineeSponsor NomineeSponsor { get; set; }
        public virtual NomineeType NomineeType { get; set; }
        public virtual ProgramYear ProgramYear { get; set; }
    }
}
