//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomineeType
    {
        public NomineeType()
        {
            this.NomineePrograms = new HashSet<NomineeProgram>();
        }
    
        public int NomineeTypeId { get; set; }
        public string NomineeType1 { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<NomineeProgram> NomineePrograms { get; set; }
    }
}
