//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominatingOrganization
    {
        public NominatingOrganization()
        {
            this.NomineeSponsors = new HashSet<NomineeSponsor>();
        }
    
        public int OrganizationId { get; set; }
        public string OrganizationName { get; set; }
    
        public virtual ICollection<NomineeSponsor> NomineeSponsors { get; set; }
    }
}
