//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomineeSponsor
    {
        public NomineeSponsor()
        {
            this.NomineePrograms = new HashSet<NomineeProgram>();
            this.NomineeSponsorPhones = new HashSet<NomineeSponsorPhone>();
        }
    
        public int NomineeSponsorId { get; set; }
        public Nullable<int> LegacyNomineeId { get; set; }
        public string Organization { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> OrganizationId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<NomineeProgram> NomineePrograms { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<NomineeSponsorPhone> NomineeSponsorPhones { get; set; }
        public virtual NominatingOrganization NominatingOrganization { get; set; }
    }
}
