//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelUserPotentialAssignment
    {
        public int SessionPanelId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ClientParticipantTypeId { get; set; }
        public Nullable<int> ClientRoleId { get; set; }
        public bool RestrictedAssignedFlag { get; set; }
        public bool RecruitedFlag { get; set; }
        public Nullable<System.DateTime> RecruitedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ParticipationMethodId { get; set; }
        public int PanelUserPotentialAssignmentId { get; set; }
        public Nullable<bool> ClientApprovalFlag { get; set; }
        public Nullable<int> ClientApprovalBy { get; set; }
        public Nullable<System.DateTime> ClientApprovalDate { get; set; }
    
        public virtual ClientParticipantType ClientParticipantType { get; set; }
        public virtual ClientRole ClientRole { get; set; }
        public virtual SessionPanel SessionPanel { get; set; }
        public virtual User User { get; set; }
        public virtual ParticipationMethod ParticipationMethod { get; set; }
        public virtual User User1 { get; set; }
    }
}
