//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelUserRegistrationDocumentContract
    {
        public int PanelUserRegistrationDocumentContractId { get; set; }
        public int PanelUserRegistrationDocumentId { get; set; }
        public int ContractStatusId { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public string BypassReason { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string ContractFileLocation { get; set; }
    
        public virtual ContractStatus ContractStatus { get; set; }
        public virtual PanelUserRegistrationDocument PanelUserRegistrationDocument { get; set; }
    }
}
