//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelApplicationReviewerCoiDetail
    {
        public int PanelApplicationReviewerCoiDetailId { get; set; }
        public int PanelApplicationReviewerExpertiseId { get; set; }
        public int ClientCoiTypeId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ClientCoiType ClientCoiType { get; set; }
        public virtual PanelApplicationReviewerExpertise PanelApplicationReviewerExpertise { get; set; }
    }
}
