//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelApplication
    {
        public PanelApplication()
        {
            this.PanelApplicationReviewerExpertises = new HashSet<PanelApplicationReviewerExpertise>();
            this.ApplicationStages = new HashSet<ApplicationStage>();
            this.PanelApplicationReviewerAssignments = new HashSet<PanelApplicationReviewerAssignment>();
            this.ApplicationReviewStatus = new HashSet<ApplicationReviewStatu>();
            this.PanelApplicationSummaries = new HashSet<PanelApplicationSummary>();
            this.UserApplicationComments = new HashSet<UserApplicationComment>();
        }
    
        public int PanelApplicationId { get; set; }
        public int SessionPanelId { get; set; }
        public int ApplicationId { get; set; }
        public Nullable<int> ReviewOrder { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual SessionPanel SessionPanel { get; set; }
        public virtual ICollection<PanelApplicationReviewerExpertise> PanelApplicationReviewerExpertises { get; set; }
        public virtual ICollection<ApplicationStage> ApplicationStages { get; set; }
        public virtual ICollection<PanelApplicationReviewerAssignment> PanelApplicationReviewerAssignments { get; set; }
        public virtual ICollection<ApplicationReviewStatu> ApplicationReviewStatus { get; set; }
        public virtual ICollection<PanelApplicationSummary> PanelApplicationSummaries { get; set; }
        public virtual ICollection<UserApplicationComment> UserApplicationComments { get; set; }
    }
}
