//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelUserRegistrationDocument
    {
        public PanelUserRegistrationDocument()
        {
            this.PanelUserRegistrationDocumentItems = new HashSet<PanelUserRegistrationDocumentItem>();
            this.PanelUserRegistrationDocumentContracts = new HashSet<PanelUserRegistrationDocumentContract>();
        }
    
        public int PanelUserRegistrationDocumentId { get; set; }
        public int PanelUserRegistrationId { get; set; }
        public int ClientRegistrationDocumentId { get; set; }
        public string DocumentFile { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DateSigned { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> SignedBy { get; set; }
        public Nullable<bool> SignedOfflineFlag { get; set; }
    
        public virtual ClientRegistrationDocument ClientRegistrationDocument { get; set; }
        public virtual PanelUserRegistration PanelUserRegistration { get; set; }
        public virtual ICollection<PanelUserRegistrationDocumentItem> PanelUserRegistrationDocumentItems { get; set; }
        public virtual ICollection<PanelUserRegistrationDocumentContract> PanelUserRegistrationDocumentContracts { get; set; }
    }
}
