//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanelStageStep
    {
        public PanelStageStep()
        {
            this.ApplicationStageSteps = new HashSet<ApplicationStageStep>();
        }
    
        public int PanelStageStepId { get; set; }
        public int PanelStageId { get; set; }
        public int StepTypeId { get; set; }
        public string StepName { get; set; }
        public int StepOrder { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ReOpenDate { get; set; }
        public Nullable<System.DateTime> ReCloseDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual PanelStage PanelStage { get; set; }
        public virtual StepType StepType { get; set; }
        public virtual ICollection<ApplicationStageStep> ApplicationStageSteps { get; set; }
    }
}
