//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationMethod
    {
        public ParticipationMethod()
        {
            this.PanelUserAssignments = new HashSet<PanelUserAssignment>();
            this.PanelUserPotentialAssignments = new HashSet<PanelUserPotentialAssignment>();
        }
    
        public int ParticipationMethodId { get; set; }
        public string ParticipationMethodLabel { get; set; }
    
        public virtual ICollection<PanelUserAssignment> PanelUserAssignments { get; set; }
        public virtual ICollection<PanelUserPotentialAssignment> PanelUserPotentialAssignments { get; set; }
    }
}
