//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneType
    {
        public PhoneType()
        {
            this.UserPhones = new HashSet<UserPhone>();
            this.UserAlternateContactPhones = new HashSet<UserAlternateContactPhone>();
            this.NomineePhones = new HashSet<NomineePhone>();
            this.NomineeSponsorPhones = new HashSet<NomineeSponsorPhone>();
        }
    
        public int PhoneTypeId { get; set; }
        public string PhoneType1 { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<UserPhone> UserPhones { get; set; }
        public virtual ICollection<UserAlternateContactPhone> UserAlternateContactPhones { get; set; }
        public virtual ICollection<NomineePhone> NomineePhones { get; set; }
        public virtual ICollection<NomineeSponsorPhone> NomineeSponsorPhones { get; set; }
    }
}
