//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public Policy()
        {
            this.PolicyNetworkRanges = new HashSet<PolicyNetworkRange>();
            this.PolicyWeekDays = new HashSet<PolicyWeekDay>();
            this.PolicyHistories = new HashSet<PolicyHistory>();
        }
    
        public int PolicyId { get; set; }
        public int ClientId { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> RestrictionTypeId { get; set; }
        public Nullable<System.TimeSpan> RestrictionStartTime { get; set; }
        public Nullable<System.TimeSpan> RestrictionEndTime { get; set; }
        public bool Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool Archived { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual PolicyRestrictionType PolicyRestrictionType { get; set; }
        public virtual PolicyType PolicyType { get; set; }
        public virtual ICollection<PolicyNetworkRange> PolicyNetworkRanges { get; set; }
        public virtual ICollection<PolicyWeekDay> PolicyWeekDays { get; set; }
        public virtual ICollection<PolicyHistory> PolicyHistories { get; set; }
    }
}
