//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyHistory
    {
        public PolicyHistory()
        {
            this.PolicyNetworkRangeHistories = new HashSet<PolicyNetworkRangeHistory>();
            this.PolicyWeekDayHistories = new HashSet<PolicyWeekDayHistory>();
        }
    
        public int PolicyHistoryId { get; set; }
        public int PolicyId { get; set; }
        public int VersionId { get; set; }
        public int ClientId { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> RestrictionTypeId { get; set; }
        public Nullable<System.TimeSpan> RestrictionStartTime { get; set; }
        public Nullable<System.TimeSpan> RestrictionEndTime { get; set; }
        public bool Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool DeletedFlag { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int PolicyStatusId { get; set; }
    
        public virtual Policy Policy { get; set; }
        public virtual ICollection<PolicyNetworkRangeHistory> PolicyNetworkRangeHistories { get; set; }
        public virtual ICollection<PolicyWeekDayHistory> PolicyWeekDayHistories { get; set; }
        public virtual PolicyStatu PolicyStatu { get; set; }
    }
}
