//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prefix
    {
        public Prefix()
        {
            this.UserInfoes = new HashSet<UserInfo>();
            this.Nominees = new HashSet<Nominee>();
        }
    
        public int PrefixId { get; set; }
        public string PrefixName { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
        public virtual ICollection<Nominee> Nominees { get; set; }
    }
}
