//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileType
    {
        public ProfileType()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int ProfileTypeId { get; set; }
        public int SortOrder { get; set; }
        public string ProfileTypeName { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
