//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramMechanism
    {
        public ProgramMechanism()
        {
            this.Applications = new HashSet<Application>();
            this.MechanismTemplates = new HashSet<MechanismTemplate>();
            this.SummaryReviewerDescriptions = new HashSet<SummaryReviewerDescription>();
            this.MechanismScoringTemplates = new HashSet<MechanismScoringTemplate>();
            this.ProgramMechanismSummaryStatements = new HashSet<ProgramMechanismSummaryStatement>();
            this.ProgramMechanismImportLogs = new HashSet<ProgramMechanismImportLog>();
        }
    
        public int ProgramMechanismId { get; set; }
        public int ProgramYearId { get; set; }
        public int ClientAwardTypeId { get; set; }
        public Nullable<int> ReceiptCycle { get; set; }
        public Nullable<int> LegacyAtmId { get; set; }
        public string AbstractFormat { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool BlindedFlag { get; set; }
        public string FundingOpportunityId { get; set; }
        public Nullable<int> ParentProgramMechanismId { get; set; }
        public Nullable<int> MechanismRelationshipTypeId { get; set; }
        public bool PartneringPiAllowedFlag { get; set; }
        public Nullable<System.DateTime> ReceiptDeadline { get; set; }
        public Nullable<int> SummarySetupLastUpdatedBy { get; set; }
        public Nullable<System.DateTime> SummarySetupLastUpdatedDate { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ClientAwardType ClientAwardType { get; set; }
        public virtual ProgramYear ProgramYear { get; set; }
        public virtual ICollection<MechanismTemplate> MechanismTemplates { get; set; }
        public virtual ICollection<SummaryReviewerDescription> SummaryReviewerDescriptions { get; set; }
        public virtual ProgramMechanism ProgramMechanism1 { get; set; }
        public virtual ProgramMechanism ProgramMechanism2 { get; set; }
        public virtual ICollection<MechanismScoringTemplate> MechanismScoringTemplates { get; set; }
        public virtual ICollection<ProgramMechanismSummaryStatement> ProgramMechanismSummaryStatements { get; set; }
        public virtual ICollection<ProgramMechanismImportLog> ProgramMechanismImportLogs { get; set; }
        public virtual User User { get; set; }
    }
}
