//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryQuestion
    {
        public RecoveryQuestion()
        {
            this.UserAccountRecoveries = new HashSet<UserAccountRecovery>();
        }
    
        public int RecoveryQuestionId { get; set; }
        public string QuestionText { get; set; }
    
        public virtual ICollection<UserAccountRecovery> UserAccountRecoveries { get; set; }
    }
}
