//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationDocumentType
    {
        public RegistrationDocumentType()
        {
            this.ClientRegistrationDocuments = new HashSet<ClientRegistrationDocument>();
        }
    
        public int RegistrationDocumentTypeId { get; set; }
        public string RegistrationDocumentName { get; set; }
    
        public virtual ICollection<ClientRegistrationDocument> ClientRegistrationDocuments { get; set; }
    }
}
