//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportParameter
    {
        public int ReportParamId { get; set; }
        public int ReportId { get; set; }
        public int ParameterId { get; set; }
        public bool Required { get; set; }
        public bool MultiSelect { get; set; }
    
        public virtual LookupReportParameter LookupReportParameter { get; set; }
    }
}
