//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.ReportPermissions1 = new HashSet<ReportPermission>();
        }
    
        public string ReportName { get; set; }
        public string ReportFileName { get; set; }
        public string ReportDescription { get; set; }
        public bool Active { get; set; }
        public int ReportGroupId { get; set; }
        public int ReportId { get; set; }
        public Nullable<int> ReportParameterGroupId { get; set; }
        public string ReportParameterGroupDesc { get; set; }
    
        public virtual LookupReportGroup LookupReportGroup { get; set; }
        public virtual ICollection<ReportPermission> ReportPermissions1 { get; set; }
    }
}
