//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewStatusType
    {
        public ReviewStatusType()
        {
            this.ReviewStatus = new HashSet<ReviewStatu>();
        }
    
        public int ReviewStatusTypeId { get; set; }
        public string StatusTypeName { get; set; }
    
        public virtual ICollection<ReviewStatu> ReviewStatus { get; set; }
    }
}
