//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewStatu
    {
        public ReviewStatu()
        {
            this.ApplicationReviewStatus = new HashSet<ApplicationReviewStatu>();
            this.MechanismTemplates = new HashSet<MechanismTemplate>();
            this.WorkflowMechanism = new HashSet<WorkflowMechanism>();
            this.ProgramMechanismSummaryStatements = new HashSet<ProgramMechanismSummaryStatement>();
        }
    
        public int ReviewStatusId { get; set; }
        public string ReviewStatusLabel { get; set; }
        public int ReviewStatusTypeId { get; set; }
    
        public virtual ICollection<ApplicationReviewStatu> ApplicationReviewStatus { get; set; }
        public virtual ReviewStatusType ReviewStatusType { get; set; }
        public virtual ICollection<MechanismTemplate> MechanismTemplates { get; set; }
        public virtual ICollection<WorkflowMechanism> WorkflowMechanism { get; set; }
        public virtual ICollection<ProgramMechanismSummaryStatement> ProgramMechanismSummaryStatements { get; set; }
    }
}
