//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleParticipantType
    {
        public int RoleParticipantTypeId { get; set; }
        public int SystemRoleId { get; set; }
        public int ClientId { get; set; }
        public int ClientParticipantTypeId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ClientParticipantType ClientParticipantType { get; set; }
        public virtual SystemRole SystemRole { get; set; }
    }
}
