//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoringTemplatePhase
    {
        public int ScoringTemplatePhaseId { get; set; }
        public int ScoringTemplateId { get; set; }
        public int StepTypeId { get; set; }
        public int StepOrder { get; set; }
        public int OverallClientScoringId { get; set; }
        public int CriteriaClientScoringId { get; set; }
    
        public virtual ClientScoringScale ClientScoringScale { get; set; }
        public virtual ClientScoringScale ClientScoringScale1 { get; set; }
        public virtual ScoringTemplate ScoringTemplate { get; set; }
        public virtual StepType StepType { get; set; }
    }
}
