//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoringTemplate
    {
        public ScoringTemplate()
        {
            this.MechanismScoringTemplates = new HashSet<MechanismScoringTemplate>();
            this.ScoringTemplatePhases = new HashSet<ScoringTemplatePhase>();
        }
    
        public int ScoringTemplateId { get; set; }
        public int ClientId { get; set; }
        public string TemplateName { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<MechanismScoringTemplate> MechanismScoringTemplates { get; set; }
        public virtual ICollection<ScoringTemplatePhase> ScoringTemplatePhases { get; set; }
    }
}
