//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceLog
    {
        public int ServiceLogId { get; set; }
        public Nullable<int> ClientServiceAccountId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string RequestEndpoint { get; set; }
        public string RequestHttpMethod { get; set; }
        public string RequestParameters { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseMessage { get; set; }
        public byte[] ResponseFileResult { get; set; }
        public string ResponseFileFormat { get; set; }
        public System.DateTime RequestDate { get; set; }
    }
}
