//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.UserAddresses = new HashSet<UserAddress>();
            this.Nominees = new HashSet<Nominee>();
            this.NomineeSponsors = new HashSet<NomineeSponsor>();
        }
    
        public int StateId { get; set; }
        public string StateAbbreviation { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
        public virtual ICollection<Nominee> Nominees { get; set; }
        public virtual ICollection<NomineeSponsor> NomineeSponsors { get; set; }
    }
}
