//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepType
    {
        public StepType()
        {
            this.ApplicationWorkflowSteps = new HashSet<ApplicationWorkflowStep>();
            this.WorkflowSteps = new HashSet<WorkflowStep>();
            this.PanelStageSteps = new HashSet<PanelStageStep>();
            this.MechanismTemplateElementScorings = new HashSet<MechanismTemplateElementScoring>();
            this.StepTypeOperations = new HashSet<StepTypeOperation>();
            this.ScoringTemplatePhases = new HashSet<ScoringTemplatePhase>();
            this.SessionPhases = new HashSet<SessionPhase>();
        }
    
        public int StepTypeId { get; set; }
        public string StepTypeName { get; set; }
        public bool CleanMarkupFlag { get; set; }
        public int ReviewStageId { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<ApplicationWorkflowStep> ApplicationWorkflowSteps { get; set; }
        public virtual ICollection<WorkflowStep> WorkflowSteps { get; set; }
        public virtual ICollection<PanelStageStep> PanelStageSteps { get; set; }
        public virtual ICollection<MechanismTemplateElementScoring> MechanismTemplateElementScorings { get; set; }
        public virtual ICollection<StepTypeOperation> StepTypeOperations { get; set; }
        public virtual ICollection<ScoringTemplatePhase> ScoringTemplatePhases { get; set; }
        public virtual ReviewStage ReviewStage { get; set; }
        public virtual ICollection<SessionPhase> SessionPhases { get; set; }
    }
}
