//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryStatementMode
    {
        public SummaryStatementMode()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int SummaryStatementModeId { get; set; }
        public string ModeLabel { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
