//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemTemplate
    {
        public SystemTemplate()
        {
            this.SystemTemplateVersions = new HashSet<SystemTemplateVersion>();
        }
    
        public int TemplateId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeID { get; set; }
        public int VersionId { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual LookupTemplateCategory LookupTemplateCategory { get; set; }
        public virtual LookupTemplateType LookupTemplateType { get; set; }
        public virtual ICollection<SystemTemplateVersion> SystemTemplateVersions { get; set; }
    }
}
