//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfiguration
    {
        public SystemConfiguration()
        {
            this.ClientConfigurations = new HashSet<ClientConfiguration>();
        }
    
        public int SystemConfigurationId { get; set; }
        public string ConfigurationName { get; set; }
        public string ConfigurationDescription { get; set; }
    
        public virtual ICollection<ClientConfiguration> ClientConfigurations { get; set; }
    }
}
