//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemTemplateVersion
    {
        public int VersionId { get; set; }
        public int TemplateId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public int VersionNumber { get; set; }
        public string Body { get; set; }
        public Nullable<int> TemplateStageID { get; set; }
        public Nullable<int> SentBy { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual LookupTemplateStage LookupTemplateStage { get; set; }
        public virtual SystemTemplate SystemTemplate { get; set; }
    }
}
