//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemOperation
    {
        public SystemOperation()
        {
            this.TaskOperations = new HashSet<TaskOperation>();
            this.StepTypeOperations = new HashSet<StepTypeOperation>();
        }
    
        public int SystemOperationId { get; set; }
        public string OperationName { get; set; }
        public string OperationDescription { get; set; }
    
        public virtual ICollection<TaskOperation> TaskOperations { get; set; }
        public virtual ICollection<StepTypeOperation> StepTypeOperations { get; set; }
    }
}
