//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemRole
    {
        public SystemRole()
        {
            this.UserSystemRoles = new HashSet<UserSystemRole>();
            this.RoleTasks = new HashSet<RoleTask>();
            this.RoleParticipantTypes = new HashSet<RoleParticipantType>();
        }
    
        public int SystemRoleId { get; set; }
        public string SystemRoleName { get; set; }
        public string SystemRoleContext { get; set; }
        public string SystemRoleCode { get; set; }
        public int SystemPriorityOrder { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<UserSystemRole> UserSystemRoles { get; set; }
        public virtual ICollection<RoleTask> RoleTasks { get; set; }
        public virtual ICollection<RoleParticipantType> RoleParticipantTypes { get; set; }
    }
}
