//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemTask
    {
        public SystemTask()
        {
            this.RoleTasks = new HashSet<RoleTask>();
            this.TaskOperations = new HashSet<TaskOperation>();
        }
    
        public int SystemTaskId { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
    
        public virtual ICollection<RoleTask> RoleTasks { get; set; }
        public virtual ICollection<TaskOperation> TaskOperations { get; set; }
    }
}
