//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCategory
    {
        public TrainingCategory()
        {
            this.PeerReviewDocuments = new HashSet<PeerReviewDocument>();
        }
    
        public int TrainingCategoryId { get; set; }
        public string CategoryName { get; set; }
        public int SortOrder { get; set; }
        public string LegacyCatTypeId { get; set; }
    
        public virtual ICollection<PeerReviewDocument> PeerReviewDocuments { get; set; }
    }
}
