//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.UserAddresses = new HashSet<UserAddress>();
            this.UserEmails = new HashSet<UserEmail>();
            this.UserPhones = new HashSet<UserPhone>();
            this.UserDegrees = new HashSet<UserDegree>();
            this.UserResumes = new HashSet<UserResume>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.UserWebsites = new HashSet<UserWebsite>();
            this.UserAlternateContacts = new HashSet<UserAlternateContact>();
            this.UserInfoChangeLogs = new HashSet<UserInfoChangeLog>();
            this.UserEvaluationLogs = new HashSet<UserEvaluationLog>();
            this.UserBlockLogs = new HashSet<UserBlockLog>();
            this.UserClientBlocks = new HashSet<UserClientBlock>();
            this.UserVendors = new HashSet<UserVendor>();
        }
    
        public int UserInfoID { get; set; }
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string BadgeName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> MilitaryRankId { get; set; }
        public Nullable<int> PrefixId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> EthnicityId { get; set; }
        public string Institution { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> MilitaryStatusTypeId { get; set; }
        public string NickName { get; set; }
        public string SuffixText { get; set; }
        public Nullable<int> AcademicRankId { get; set; }
        public Nullable<int> ProfessionalAffiliationId { get; set; }
        public bool DegreeNotApplicable { get; set; }
        public string Expertise { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
        public virtual ICollection<UserEmail> UserEmails { get; set; }
        public virtual ICollection<UserPhone> UserPhones { get; set; }
        public virtual Ethnicity Ethnicity { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MilitaryRank MilitaryRank { get; set; }
        public virtual Prefix Prefix { get; set; }
        public virtual ICollection<UserDegree> UserDegrees { get; set; }
        public virtual ICollection<UserResume> UserResumes { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<UserWebsite> UserWebsites { get; set; }
        public virtual ICollection<UserAlternateContact> UserAlternateContacts { get; set; }
        public virtual MilitaryStatusType MilitaryStatusType { get; set; }
        public virtual ICollection<UserInfoChangeLog> UserInfoChangeLogs { get; set; }
        public virtual ICollection<UserEvaluationLog> UserEvaluationLogs { get; set; }
        public virtual ICollection<UserBlockLog> UserBlockLogs { get; set; }
        public virtual ICollection<UserClientBlock> UserClientBlocks { get; set; }
        public virtual ICollection<UserVendor> UserVendors { get; set; }
    }
}
