//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoChangeType
    {
        public UserInfoChangeType()
        {
            this.UserInfoChangeLogs = new HashSet<UserInfoChangeLog>();
        }
    
        public int UserInfoChangeTypeId { get; set; }
        public string Label { get; set; }
        public int SortOrder { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
    
        public virtual ICollection<UserInfoChangeLog> UserInfoChangeLogs { get; set; }
    }
}
