//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoChangeLog
    {
        public int UserInfoChangeLogId { get; set; }
        public int UserInfoId { get; set; }
        public int UserInfoChangeTypeId { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public bool ReviewedFlag { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int Identifier { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfoChangeType UserInfoChangeType { get; set; }
        public virtual User CreatedByUser { get; set; }
        public virtual User ModifiedByUser { get; set; }
    }
}
