//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAlternateContact
    {
        public UserAlternateContact()
        {
            this.UserAlternateContactPhones = new HashSet<UserAlternateContactPhone>();
        }
    
        public int UserAlternateContactId { get; set; }
        public int UserInfoId { get; set; }
        public int AlternateContactTypeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public bool PrimaryFlag { get; set; }
        public Nullable<int> ProfessionalAffiliationId { get; set; }
    
        public virtual AlternateContactType AlternateContactType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<UserAlternateContactPhone> UserAlternateContactPhones { get; set; }
    }
}
