//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccountStatusChangeLog
    {
        public int UserAccountStatusChangeLogId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> NewAccountStatusId { get; set; }
        public Nullable<int> OldAccountStatusId { get; set; }
        public Nullable<int> NewAccountStatusReasonId { get; set; }
        public Nullable<int> OldAccountStatusReasonId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual AccountStatu AccountStatu { get; set; }
        public virtual AccountStatu AccountStatu1 { get; set; }
        public virtual AccountStatusReason AccountStatusReason { get; set; }
        public virtual AccountStatusReason AccountStatusReason1 { get; set; }
    }
}
