//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBlockLog
    {
        public UserBlockLog()
        {
            this.UserBlockLogClients = new HashSet<UserBlockLogClient>();
        }
    
        public int UserBlockLogId { get; set; }
        public int UserInfoId { get; set; }
        public int EnteredByUserId { get; set; }
        public string BlockComment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual ICollection<UserBlockLogClient> UserBlockLogClients { get; set; }
    }
}
