//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPhone
    {
        public int PhoneID { get; set; }
        public int UserInfoID { get; set; }
        public string Phone { get; set; }
        public string Extension { get; set; }
        public Nullable<bool> International { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> PhoneTypeId { get; set; }
        public Nullable<int> LegacyPhoneId { get; set; }
        public Nullable<bool> PrimaryFlag { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual PhoneType PhoneType { get; set; }
    }
}
