//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sra.P2rmis.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorType
    {
        public VendorType()
        {
            this.UserVendors = new HashSet<UserVendor>();
        }
    
        public int VendorTypeId { get; set; }
        public string VendorTypeName { get; set; }
    
        public virtual ICollection<UserVendor> UserVendors { get; set; }
    }
}
