CREATE TABLE [dbo].[TempTriageTool]
(
	[TempTriageToolId] INT NOT NULL IDENTITY,
	[LogNo_Assign] [nvarchar](15) NULL,
	[CritiqueID] [int] NULL,
	[LogNo] [nvarchar](12) NULL,
	[AwardType] [nvarchar](10) NULL,
	[AwardShortDesc] [nvarchar](50) NULL,
	[EvalLabel1] [nvarchar](250) NULL,
	[ECMCriteriaScore1] [decimal](18, 1) NULL,
	[EvalLabel2] [nvarchar](250) NULL,
	[ECMCriteriaScore2] [decimal](18, 1) NULL,
	[EvalLabel3] [nvarchar](250) NULL,
	[ECMCriteriaScore3] [decimal](18, 1) NULL,
	[EvalLabel4] [nvarchar](250) NULL,
	[ECMCriteriaScore4] [decimal](18, 1) NULL,
	[EvalLabel5] [nvarchar](250) NULL,
	[ECMCriteriaScore5] [decimal](18, 1) NULL,
	[EvalLabel6] [nvarchar](250) NULL,
	[ECMCriteriaScore6] [decimal](18, 1) NULL,
	[EvalLabel7] [nvarchar](250) NULL,
	[ECMCriteriaScore7] [decimal](18, 1) NULL,
	[EvalLabel8] [nvarchar](250) NULL,
	[ECMCriteriaScore8] [decimal](18, 1) NULL,
	[EvalLabel9] [nvarchar](250) NULL,
	[ECMCriteriaScore9] [decimal](18, 1) NULL,
	[EvalLabel10] [nvarchar](250) NULL,
	[ECMCriteriaScore10] [decimal](18, 1) NULL,
	[PanelAbrv] [nvarchar](255) NULL,
	[AssignOrder] [int] NULL,
	[FY] [int] NULL,
	[Program] [nvarchar](250) NULL,
	[Award] [nvarchar](250) NULL, 
    CONSTRAINT [PK_TempTriageTool] PRIMARY KEY ([TempTriageToolId])
)
