--This script sets all foreign keys in the db to cascade.
--Run regular db deployment afterward to reset
--DO NOT INCLUDE IN DEPLOY PROCESS 
select
  DropStmt = 'ALTER TABLE [' + ForeignKeys.ForeignTableSchema + 
      '].[' + ForeignKeys.ForeignTableName + 
      '] DROP CONSTRAINT [' + ForeignKeys.ForeignKeyName + ']; '
,  CreateStmt = 'ALTER TABLE [' + ForeignKeys.ForeignTableSchema + 
      '].[' + ForeignKeys.ForeignTableName + 
      '] WITH CHECK ADD CONSTRAINT [' +  ForeignKeys.ForeignKeyName + 
      '] FOREIGN KEY([' + ForeignKeys.ForeignTableColumn + 
      ']) REFERENCES [' + schema_name(sys.objects.schema_id) + '].[' +
  sys.objects.[name] + ']([' +
  sys.columns.[name] + ']) ON DELETE CASCADE; '
 from sys.objects
  inner join sys.columns
    on (sys.columns.[object_id] = sys.objects.[object_id])
  inner join (
    select sys.foreign_keys.[name] as ForeignKeyName
     ,schema_name(sys.objects.schema_id) as ForeignTableSchema
     ,sys.objects.[name] as ForeignTableName
     ,sys.columns.[name]  as ForeignTableColumn
     ,sys.foreign_keys.referenced_object_id as referenced_object_id
     ,sys.foreign_key_columns.referenced_column_id as referenced_column_id
     from sys.foreign_keys
      inner join sys.foreign_key_columns
        on (sys.foreign_key_columns.constraint_object_id
          = sys.foreign_keys.[object_id])
      inner join sys.objects
        on (sys.objects.[object_id]
          = sys.foreign_keys.parent_object_id)
        inner join sys.columns
          on (sys.columns.[object_id]
            = sys.objects.[object_id])
           and (sys.columns.column_id
            = sys.foreign_key_columns.parent_column_id)
    ) ForeignKeys
    on (ForeignKeys.referenced_object_id = sys.objects.[object_id])
     and (ForeignKeys.referenced_column_id = sys.columns.column_id)
 where (sys.objects.[type] = 'U')
  and (sys.objects.[name] not in ('sysdiagrams'))
  --ALTER STATEMENTS
ALTER TABLE [dbo].[PanelStage] DROP CONSTRAINT [FK_PanelStage_Panel]; 	ALTER TABLE [dbo].[PanelStage] WITH CHECK ADD CONSTRAINT [FK_PanelStage_Panel] FOREIGN KEY([SessionPanelId]) REFERENCES [dbo].[SessionPanel]([SessionPanelId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PanelUserPotentialAssignment] DROP CONSTRAINT [FK_PanelUserPotentialAssignment_SessionPanel]; 	ALTER TABLE [dbo].[PanelUserPotentialAssignment] WITH CHECK ADD CONSTRAINT [FK_PanelUserPotentialAssignment_SessionPanel] FOREIGN KEY([SessionPanelId]) REFERENCES [dbo].[SessionPanel]([SessionPanelId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[CommunicationLog] DROP CONSTRAINT [FK_CommunicationLog_SessionPanel]; 	ALTER TABLE [dbo].[CommunicationLog] WITH CHECK ADD CONSTRAINT [FK_CommunicationLog_SessionPanel] FOREIGN KEY([SessionPanelId]) REFERENCES [dbo].[SessionPanel]([SessionPanelId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationStageStepDiscussion] DROP CONSTRAINT [FK_ApplicationStageStepDiscussion_ApplicationStageStepId]; 	ALTER TABLE [dbo].[ApplicationStageStepDiscussion] WITH CHECK ADD CONSTRAINT [FK_ApplicationStageStepDiscussion_ApplicationStageStepId] FOREIGN KEY([ApplicationStageStepId]) REFERENCES [dbo].[ApplicationStageStep]([ApplicationStageStepId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationStageStepDiscussionComment] DROP CONSTRAINT [FK_ApplicationStageStepDiscussionComment_ApplicationStageStepDiscussion]; 	ALTER TABLE [dbo].[ApplicationStageStepDiscussionComment] WITH CHECK ADD CONSTRAINT [FK_ApplicationStageStepDiscussionComment_ApplicationStageStepDiscussion] FOREIGN KEY([ApplicationStageStepDiscussionId]) REFERENCES [dbo].[ApplicationStageStepDiscussion]([ApplicationStageStepDiscussionId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PanelApplication] DROP CONSTRAINT [FK_PanelApplication_Panel]; 	ALTER TABLE [dbo].[PanelApplication] WITH CHECK ADD CONSTRAINT [FK_PanelApplication_Panel] FOREIGN KEY([SessionPanelId]) REFERENCES [dbo].[SessionPanel]([SessionPanelId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PanelUserAssignment] DROP CONSTRAINT [FK_PanelUserAssignment_SessionPanel]; 	ALTER TABLE [dbo].[PanelUserAssignment] WITH CHECK ADD CONSTRAINT [FK_PanelUserAssignment_SessionPanel] FOREIGN KEY([SessionPanelId]) REFERENCES [dbo].[SessionPanel]([SessionPanelId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ProgramPanel] DROP CONSTRAINT [FK_ProgramPanel_SessionPanel]; 	ALTER TABLE [dbo].[ProgramPanel] WITH CHECK ADD CONSTRAINT [FK_ProgramPanel_SessionPanel] FOREIGN KEY([SessionPanelId]) REFERENCES [dbo].[SessionPanel]([SessionPanelId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[MeetingRegistrationAttendance] DROP CONSTRAINT [FK_MeetingRegistrationAttendance_MeetingRegistrationId]; 	ALTER TABLE [dbo].[MeetingRegistrationAttendance] WITH CHECK ADD CONSTRAINT [FK_MeetingRegistrationAttendance_MeetingRegistrationId] FOREIGN KEY([MeetingRegistrationId]) REFERENCES [dbo].[MeetingRegistration]([MeetingRegistrationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[MeetingRegistrationHotel] DROP CONSTRAINT [FK_MeetingRegistrationHotel_MeetingRegistration]; 	ALTER TABLE [dbo].[MeetingRegistrationHotel] WITH CHECK ADD CONSTRAINT [FK_MeetingRegistrationHotel_MeetingRegistration] FOREIGN KEY([MeetingRegistrationId]) REFERENCES [dbo].[MeetingRegistration]([MeetingRegistrationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[MeetingRegistrationTravel] DROP CONSTRAINT [FK_MeetingRegistrationTravel_MeetingRegistration]; 	ALTER TABLE [dbo].[MeetingRegistrationTravel] WITH CHECK ADD CONSTRAINT [FK_MeetingRegistrationTravel_MeetingRegistration] FOREIGN KEY([MeetingRegistrationId]) REFERENCES [dbo].[MeetingRegistration]([MeetingRegistrationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[SessionPanel] DROP CONSTRAINT [FK_SessionPanel_MeetingSession]; 	ALTER TABLE [dbo].[SessionPanel] WITH CHECK ADD CONSTRAINT [FK_SessionPanel_MeetingSession] FOREIGN KEY([MeetingSessionId]) REFERENCES [dbo].[MeetingSession]([MeetingSessionId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[SessionPayRate] DROP CONSTRAINT [FK_SessionPayRate_MeetingSession]; 	ALTER TABLE [dbo].[SessionPayRate] WITH CHECK ADD CONSTRAINT [FK_SessionPayRate_MeetingSession] FOREIGN KEY([MeetingSessionId]) REFERENCES [dbo].[MeetingSession]([MeetingSessionId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[SessionPhase] DROP CONSTRAINT [FK_SessionPhase_MeetingSession]; 	ALTER TABLE [dbo].[SessionPhase] WITH CHECK ADD CONSTRAINT [FK_SessionPhase_MeetingSession] FOREIGN KEY([MeetingSessionId]) REFERENCES [dbo].[MeetingSession]([MeetingSessionId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PanelUserRegistrationDocument] DROP CONSTRAINT [FK_PanelUserRegistrationDocument_PanelUserRegistrationId]; 	ALTER TABLE [dbo].[PanelUserRegistrationDocument] WITH CHECK ADD CONSTRAINT [FK_PanelUserRegistrationDocument_PanelUserRegistrationId] FOREIGN KEY([PanelUserRegistrationId]) REFERENCES [dbo].[PanelUserRegistration]([PanelUserRegistrationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PanelApplicationReviewerExpertise] DROP CONSTRAINT [FK_PanelApplicationReviewerExpertise_PanelApplication]; 	ALTER TABLE [dbo].[PanelApplicationReviewerExpertise] WITH CHECK ADD CONSTRAINT [FK_PanelApplicationReviewerExpertise_PanelApplication] FOREIGN KEY([PanelApplicationId]) REFERENCES [dbo].[PanelApplication]([PanelApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PanelApplicationSummary] DROP CONSTRAINT [FK_PanelApplicationSummary_PanelApplication]; 	ALTER TABLE [dbo].[PanelApplicationSummary] WITH CHECK ADD CONSTRAINT [FK_PanelApplicationSummary_PanelApplication] FOREIGN KEY([PanelApplicationId]) REFERENCES [dbo].[PanelApplication]([PanelApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationStage] DROP CONSTRAINT [FK_ApplicationStage_PanelApplication]; 	ALTER TABLE [dbo].[ApplicationStage] WITH CHECK ADD CONSTRAINT [FK_ApplicationStage_PanelApplication] FOREIGN KEY([PanelApplicationId]) REFERENCES [dbo].[PanelApplication]([PanelApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[UserApplicationComment] DROP CONSTRAINT [FK_UserApplicationComment_PanelApplicationId]; 	ALTER TABLE [dbo].[UserApplicationComment] WITH CHECK ADD CONSTRAINT [FK_UserApplicationComment_PanelApplicationId] FOREIGN KEY([PanelApplicationId]) REFERENCES [dbo].[PanelApplication]([PanelApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PanelApplicationReviewerAssignment] DROP CONSTRAINT [FK_PanelApplicationReviewerAssignment_PanelApplication]; 	ALTER TABLE [dbo].[PanelApplicationReviewerAssignment] WITH CHECK ADD CONSTRAINT [FK_PanelApplicationReviewerAssignment_PanelApplication] FOREIGN KEY([PanelApplicationId]) REFERENCES [dbo].[PanelApplication]([PanelApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationReviewStatus] DROP CONSTRAINT [FK_ApplicationReviewStatus_PanelApplication]; 	ALTER TABLE [dbo].[ApplicationReviewStatus] WITH CHECK ADD CONSTRAINT [FK_ApplicationReviewStatus_PanelApplication] FOREIGN KEY([PanelApplicationId]) REFERENCES [dbo].[PanelApplication]([PanelApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PanelUserRegistrationDocumentItem] DROP CONSTRAINT [FK_PanelUserRegistrationDocumentItem_PanelUserRegistrationDocument]; 	ALTER TABLE [dbo].[PanelUserRegistrationDocumentItem] WITH CHECK ADD CONSTRAINT [FK_PanelUserRegistrationDocumentItem_PanelUserRegistrationDocument] FOREIGN KEY([PanelUserRegistrationDocumentId]) REFERENCES [dbo].[PanelUserRegistrationDocument]([PanelUserRegistrationDocumentId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationPersonnel] DROP CONSTRAINT [FK_ApplicationPersonnel_Application]; 	ALTER TABLE [dbo].[ApplicationPersonnel] WITH CHECK ADD CONSTRAINT [FK_ApplicationPersonnel_Application] FOREIGN KEY([ApplicationId]) REFERENCES [dbo].[Application]([ApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationBudget] DROP CONSTRAINT [FK_ApplicationBudget_Application]; 	ALTER TABLE [dbo].[ApplicationBudget] WITH CHECK ADD CONSTRAINT [FK_ApplicationBudget_Application] FOREIGN KEY([ApplicationId]) REFERENCES [dbo].[Application]([ApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationCompliance] DROP CONSTRAINT [FK_ApplicationCompliance_Application]; 	ALTER TABLE [dbo].[ApplicationCompliance] WITH CHECK ADD CONSTRAINT [FK_ApplicationCompliance_Application] FOREIGN KEY([ApplicationId]) REFERENCES [dbo].[Application]([ApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationDefaultWorkflow] DROP CONSTRAINT [FK_ApplicationDefaultWorkflow_Application]; 	ALTER TABLE [dbo].[ApplicationDefaultWorkflow] WITH CHECK ADD CONSTRAINT [FK_ApplicationDefaultWorkflow_Application] FOREIGN KEY([ApplicationId]) REFERENCES [dbo].[Application]([ApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationInfo] DROP CONSTRAINT [FK_ApplicationInfo_Application]; 	ALTER TABLE [dbo].[ApplicationInfo] WITH CHECK ADD CONSTRAINT [FK_ApplicationInfo_Application] FOREIGN KEY([ApplicationId]) REFERENCES [dbo].[Application]([ApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationResearchCategory] DROP CONSTRAINT [FK_ApplicationResearchCategory_Application]; 	ALTER TABLE [dbo].[ApplicationResearchCategory] WITH CHECK ADD CONSTRAINT [FK_ApplicationResearchCategory_Application] FOREIGN KEY([ApplicationId]) REFERENCES [dbo].[Application]([ApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationText] DROP CONSTRAINT [FK_ApplicationText_Application]; 	ALTER TABLE [dbo].[ApplicationText] WITH CHECK ADD CONSTRAINT [FK_ApplicationText_Application] FOREIGN KEY([ApplicationId]) REFERENCES [dbo].[Application]([ApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PanelApplication] DROP CONSTRAINT [FK_PanelApplication_Application]; 	ALTER TABLE [dbo].[PanelApplication] WITH CHECK ADD CONSTRAINT [FK_PanelApplication_Application] FOREIGN KEY([ApplicationId]) REFERENCES [dbo].[Application]([ApplicationId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationTemplateElement] DROP CONSTRAINT [FK_ApplicationTemplateElement_ApplicationTemplate]; 	ALTER TABLE [dbo].[ApplicationTemplateElement] WITH CHECK ADD CONSTRAINT [FK_ApplicationTemplateElement_ApplicationTemplate] FOREIGN KEY([ApplicationTemplateId]) REFERENCES [dbo].[ApplicationTemplate]([ApplicationTemplateId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationWorkflow] DROP CONSTRAINT [FK_ApplicationWorkflow_ApplicationTemplate]; 	
ALTER TABLE [dbo].[PanelApplicationReviewerCoiDetail] DROP CONSTRAINT [FK_PanelApplicationReviewerCoiDetail_PanelApplicationReviewerExpertise]; 	ALTER TABLE [dbo].[PanelApplicationReviewerCoiDetail] WITH CHECK ADD CONSTRAINT [FK_PanelApplicationReviewerCoiDetail_PanelApplicationReviewerExpertise] FOREIGN KEY([PanelApplicationReviewerExpertiseId]) REFERENCES [dbo].[PanelApplicationReviewerExpertise]([PanelApplicationReviewerExpertiseId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationStageStep] DROP CONSTRAINT [FK_ApplicationStageStep_ApplicationStage]; 	ALTER TABLE [dbo].[ApplicationStageStep] WITH CHECK ADD CONSTRAINT [FK_ApplicationStageStep_ApplicationStage] FOREIGN KEY([ApplicationStageId]) REFERENCES [dbo].[ApplicationStage]([ApplicationStageId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationTemplate] DROP CONSTRAINT [FK_ApplicationTemplate_PanelApplicationStage]; 	
ALTER TABLE [dbo].[ApplicationWorkflow] DROP CONSTRAINT [FK_ApplicationWorkflow_ApplicationStage]; 	ALTER TABLE [dbo].[ApplicationWorkflow] WITH CHECK ADD CONSTRAINT [FK_ApplicationWorkflow_ApplicationStage] FOREIGN KEY([ApplicationStageId]) REFERENCES [dbo].[ApplicationStage]([ApplicationStageId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationWorkflowStepElement] DROP CONSTRAINT [FK_ApplicationWorkflowStepElement_ApplicationTemplateElement]; 	
ALTER TABLE [dbo].[PanelStageStep] DROP CONSTRAINT [FK_PanelStageStep_PanelStage]; 	ALTER TABLE [dbo].[PanelStageStep] WITH CHECK ADD CONSTRAINT [FK_PanelStageStep_PanelStage] FOREIGN KEY([PanelStageId]) REFERENCES [dbo].[PanelStage]([PanelStageId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationWorkflowStep] DROP CONSTRAINT [FK_ApplicationWorkflowStep_ApplicationWorkflow]; 	ALTER TABLE [dbo].[ApplicationWorkflowStep] WITH CHECK ADD CONSTRAINT [FK_ApplicationWorkflowStep_ApplicationWorkflow] FOREIGN KEY([ApplicationWorkflowId]) REFERENCES [dbo].[ApplicationWorkflow]([ApplicationWorkflowId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationWorkflowSummaryStatement] DROP CONSTRAINT [FK_ApplicationWorkflowSummaryStatement_ApplicationWorkflow]; 	ALTER TABLE [dbo].[ApplicationWorkflowSummaryStatement] WITH CHECK ADD CONSTRAINT [FK_ApplicationWorkflowSummaryStatement_ApplicationWorkflow] FOREIGN KEY([ApplicationWorkflowId]) REFERENCES [dbo].[ApplicationWorkflow]([ApplicationWorkflowId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationStageStep] DROP CONSTRAINT [FK_ApplicationStageStep_PanelStageStep]; 	
ALTER TABLE [dbo].[ApplicationWorkflowStepElementContentHistory] DROP CONSTRAINT [FK_ApplicationWorkflowStepElementContentHistory_ApplicationWorkflowStepWorkLog]; 	ALTER TABLE [dbo].[ApplicationWorkflowStepElementContentHistory] WITH CHECK ADD CONSTRAINT [FK_ApplicationWorkflowStepElementContentHistory_ApplicationWorkflowStepWorkLog] FOREIGN KEY([ApplicationWorkflowStepWorkLog]) REFERENCES [dbo].[ApplicationWorkflowStepWorkLog]([ApplicationWorkflowStepWorkLogId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[MechanismTemplate] DROP CONSTRAINT [FK_MechanismTemplate_ProgramMechanism]; 	ALTER TABLE [dbo].[MechanismTemplate] WITH CHECK ADD CONSTRAINT [FK_MechanismTemplate_ProgramMechanism] FOREIGN KEY([ProgramMechanismId]) REFERENCES [dbo].[ProgramMechanism]([ProgramMechanismId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[SummaryReviewerDescription] DROP CONSTRAINT [FK_SummaryReviewerDescription_ProgramMechanism]; 	ALTER TABLE [dbo].[SummaryReviewerDescription] WITH CHECK ADD CONSTRAINT [FK_SummaryReviewerDescription_ProgramMechanism] FOREIGN KEY([ProgramMechanismId]) REFERENCES [dbo].[ProgramMechanism]([ProgramMechanismId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ProgramMechanism] DROP CONSTRAINT [FK_ProgramMechanism_ParentProgramMechanism]; 	
ALTER TABLE [dbo].[Application] DROP CONSTRAINT [FK_Application_ProgramMechanism]; 	ALTER TABLE [dbo].[Application] WITH CHECK ADD CONSTRAINT [FK_Application_ProgramMechanism] FOREIGN KEY([ProgramMechanismId]) REFERENCES [dbo].[ProgramMechanism]([ProgramMechanismId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ProgramMechanismSummaryStatement] DROP CONSTRAINT [FK_ProgramMechanismSummaryStatement_ProgramMechanism]; 	ALTER TABLE [dbo].[ProgramMechanismSummaryStatement] WITH CHECK ADD CONSTRAINT [FK_ProgramMechanismSummaryStatement_ProgramMechanism] FOREIGN KEY([ProgramMechanismId]) REFERENCES [dbo].[ProgramMechanism]([ProgramMechanismId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[MechanismScoringTemplate] DROP CONSTRAINT [FK_MechanismScoringTemplate_ProgramMechanism]; 	ALTER TABLE [dbo].[MechanismScoringTemplate] WITH CHECK ADD CONSTRAINT [FK_MechanismScoringTemplate_ProgramMechanism] FOREIGN KEY([ProgramMechanismId]) REFERENCES [dbo].[ProgramMechanism]([ProgramMechanismId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[MeetingRegistration] DROP CONSTRAINT [FK_MeetingRegistration_PanelUserAssignment]; 	ALTER TABLE [dbo].[MeetingRegistration] WITH CHECK ADD CONSTRAINT [FK_MeetingRegistration_PanelUserAssignment] FOREIGN KEY([PanelUserAssignmentId]) REFERENCES [dbo].[PanelUserAssignment]([PanelUserAssignmentId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PanelUserRegistration] DROP CONSTRAINT [FK_PanelUserRegistration_PanelUserAssignment]; 	ALTER TABLE [dbo].[PanelUserRegistration] WITH CHECK ADD CONSTRAINT [FK_PanelUserRegistration_PanelUserAssignment] FOREIGN KEY([PanelUserAssignmentId]) REFERENCES [dbo].[PanelUserAssignment]([PanelUserAssignmentId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationWorkflow] DROP CONSTRAINT [FK_ApplicationWorkflow_PanelUserAssignment]; 	
ALTER TABLE [dbo].[CommunicationLogRecipient] DROP CONSTRAINT [FK_CommunicationLogRecipient_PanelUserAssignment]; 	ALTER TABLE [dbo].[CommunicationLogRecipient] WITH CHECK ADD CONSTRAINT [FK_CommunicationLogRecipient_PanelUserAssignment] FOREIGN KEY([PanelUserAssignmentId]) REFERENCES [dbo].[PanelUserAssignment]([PanelUserAssignmentId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PanelApplicationReviewerAssignment] DROP CONSTRAINT [FK_PanelApplicationReviewerAssignment_PanelUserAssignment]; 	
ALTER TABLE [dbo].[PanelApplicationReviewerExpertise] DROP CONSTRAINT [FK_PanelApplicationReviewerExpertise_PanelUserAssignment]; 	
ALTER TABLE [dbo].[ReviewerEvaluation] DROP CONSTRAINT [FK_ReviewerEvaluation_PanelUserAssignment]; 	ALTER TABLE [dbo].[ReviewerEvaluation] WITH CHECK ADD CONSTRAINT [FK_ReviewerEvaluation_PanelUserAssignment] FOREIGN KEY([PanelUserAssignmentId]) REFERENCES [dbo].[PanelUserAssignment]([PanelUserAssignmentId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationSummaryLog] DROP CONSTRAINT [FK_ApplicationSummaryLog_ApplicationWorkflowStep]; 	ALTER TABLE [dbo].[ApplicationSummaryLog] WITH CHECK ADD CONSTRAINT [FK_ApplicationSummaryLog_ApplicationWorkflowStep] FOREIGN KEY([ApplicationWorkflowStepId]) REFERENCES [dbo].[ApplicationWorkflowStep]([ApplicationWorkflowStepId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationWorkflowStepWorkLog] DROP CONSTRAINT [FK_WorkLog_ApplicationWorkflowStep]; 	ALTER TABLE [dbo].[ApplicationWorkflowStepWorkLog] WITH CHECK ADD CONSTRAINT [FK_WorkLog_ApplicationWorkflowStep] FOREIGN KEY([ApplicationWorkflowStepId]) REFERENCES [dbo].[ApplicationWorkflowStep]([ApplicationWorkflowStepId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationWorkflowStepAssignment] DROP CONSTRAINT [FK_StepAssignment_ApplicationWorkflowStep]; 	ALTER TABLE [dbo].[ApplicationWorkflowStepAssignment] WITH CHECK ADD CONSTRAINT [FK_StepAssignment_ApplicationWorkflowStep] FOREIGN KEY([ApplicationWorkflowStepId]) REFERENCES [dbo].[ApplicationWorkflowStep]([ApplicationWorkflowStepId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationWorkflowStepElement] DROP CONSTRAINT [FK_ApplicationWorkflowStepElement_ApplicationWorkflowStep]; 	ALTER TABLE [dbo].[ApplicationWorkflowStepElement] WITH CHECK ADD CONSTRAINT [FK_ApplicationWorkflowStepElement_ApplicationWorkflowStep] FOREIGN KEY([ApplicationWorkflowStepId]) REFERENCES [dbo].[ApplicationWorkflowStep]([ApplicationWorkflowStepId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PeerReviewDocumentAccess] DROP CONSTRAINT [FK_PeerReviewDocumentAccess_PeerReviewDocument]; 	ALTER TABLE [dbo].[PeerReviewDocumentAccess] WITH CHECK ADD CONSTRAINT [FK_PeerReviewDocumentAccess_PeerReviewDocument] FOREIGN KEY([PeerReviewDocumentId]) REFERENCES [dbo].[PeerReviewDocument]([PeerReviewDocumentId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[UserPeerReviewDocument] DROP CONSTRAINT [FK_UserPeerReviewDocument_PeerReviewDocument]; 	ALTER TABLE [dbo].[UserPeerReviewDocument] WITH CHECK ADD CONSTRAINT [FK_UserPeerReviewDocument_PeerReviewDocument] FOREIGN KEY([PeerReviewDocumentId]) REFERENCES [dbo].[PeerReviewDocument]([PeerReviewDocumentId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationWorkflowStepElementContent] DROP CONSTRAINT [FK_ApplicationWorkflowStepElementContent_ApplicationWorkflowStepElement]; 	ALTER TABLE [dbo].[ApplicationWorkflowStepElementContent] WITH CHECK ADD CONSTRAINT [FK_ApplicationWorkflowStepElementContent_ApplicationWorkflowStepElement] FOREIGN KEY([ApplicationWorkflowStepElementId]) REFERENCES [dbo].[ApplicationWorkflowStepElement]([ApplicationWorkflowStepElementId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationWorkflowStepElementComment] DROP CONSTRAINT [FK_ApplicationWorkflowStepElementComment_ApplicationWorkflowStepElement]; 	ALTER TABLE [dbo].[ApplicationWorkflowStepElementComment] WITH CHECK ADD CONSTRAINT [FK_ApplicationWorkflowStepElementComment_ApplicationWorkflowStepElement] FOREIGN KEY([ApplicationWorkflowStepElementId]) REFERENCES [dbo].[ApplicationWorkflowStepElement]([ApplicationWorkflowStepElementId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ProgramPanel] DROP CONSTRAINT [FK_ProgramPanel_ProgramYear]; 	ALTER TABLE [dbo].[ProgramPanel] WITH CHECK ADD CONSTRAINT [FK_ProgramPanel_ProgramYear] FOREIGN KEY([ProgramYearId]) REFERENCES [dbo].[ProgramYear]([ProgramYearId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[UserPeerReviewDocument] DROP CONSTRAINT [FK_UserPeerReviewDocument_ProgramYear]; 	ALTER TABLE [dbo].[UserPeerReviewDocument] WITH CHECK ADD CONSTRAINT [FK_UserPeerReviewDocument_ProgramYear] FOREIGN KEY([ProgramYearId]) REFERENCES [dbo].[ProgramYear]([ProgramYearId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ProgramUserAssignment] DROP CONSTRAINT [FK_ProgramUserAssignment_ProgramYear]; 	ALTER TABLE [dbo].[ProgramUserAssignment] WITH CHECK ADD CONSTRAINT [FK_ProgramUserAssignment_ProgramYear] FOREIGN KEY([ProgramYearId]) REFERENCES [dbo].[ProgramYear]([ProgramYearId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ProgramPayRate] DROP CONSTRAINT [FK_ProgramPayRate_ProgramYear]; 	ALTER TABLE [dbo].[ProgramPayRate] WITH CHECK ADD CONSTRAINT [FK_ProgramPayRate_ProgramYear] FOREIGN KEY([ProgramYearId]) REFERENCES [dbo].[ProgramYear]([ProgramYearId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ProgramEmailTemplate] DROP CONSTRAINT [FK_ProgramEmailTemplate_ProgramYear]; 	ALTER TABLE [dbo].[ProgramEmailTemplate] WITH CHECK ADD CONSTRAINT [FK_ProgramEmailTemplate_ProgramYear] FOREIGN KEY([ProgramYearId]) REFERENCES [dbo].[ProgramYear]([ProgramYearId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ProgramMeetingInformation] DROP CONSTRAINT [FK_ProgramMeetingInformation_ProgramYear]; 	ALTER TABLE [dbo].[ProgramMeetingInformation] WITH CHECK ADD CONSTRAINT [FK_ProgramMeetingInformation_ProgramYear] FOREIGN KEY([ProgramYearId]) REFERENCES [dbo].[ProgramYear]([ProgramYearId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[TrainingDocument] DROP CONSTRAINT [FK_TrainingDocument_ProgramYear]; 	ALTER TABLE [dbo].[TrainingDocument] WITH CHECK ADD CONSTRAINT [FK_TrainingDocument_ProgramYear] FOREIGN KEY([ProgramYearId]) REFERENCES [dbo].[ProgramYear]([ProgramYearId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ProgramMeeting] DROP CONSTRAINT [FK_ProgramMeeting_ProgramYear]; 	ALTER TABLE [dbo].[ProgramMeeting] WITH CHECK ADD CONSTRAINT [FK_ProgramMeeting_ProgramYear] FOREIGN KEY([ProgramYearId]) REFERENCES [dbo].[ProgramYear]([ProgramYearId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ProgramMechanism] DROP CONSTRAINT [FK_ProgramMechanism_ProgramYear]; 	ALTER TABLE [dbo].[ProgramMechanism] WITH CHECK ADD CONSTRAINT [FK_ProgramMechanism_ProgramYear] FOREIGN KEY([ProgramYearId]) REFERENCES [dbo].[ProgramYear]([ProgramYearId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationTemplate] DROP CONSTRAINT [FK_ApplicationTemplate_MechanismTemplate]; 	ALTER TABLE [dbo].[ApplicationTemplate] WITH CHECK ADD CONSTRAINT [FK_ApplicationTemplate_MechanismTemplate] FOREIGN KEY([MechanismTemplateId]) REFERENCES [dbo].[MechanismTemplate]([MechanismTemplateId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[MechanismTemplateElement] DROP CONSTRAINT [FK_MechanismTemplateElement_MechanismTemplate]; 	ALTER TABLE [dbo].[MechanismTemplateElement] WITH CHECK ADD CONSTRAINT [FK_MechanismTemplateElement_MechanismTemplate] FOREIGN KEY([MechanismTemplateId]) REFERENCES [dbo].[MechanismTemplate]([MechanismTemplateId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[PeerReviewDocument] DROP CONSTRAINT [FK_PeerReviewDocument_ClientProgram]; 	
ALTER TABLE [dbo].[ProgramYear] DROP CONSTRAINT [FK_ProgramYear_ClientProgram]; 	ALTER TABLE [dbo].[ProgramYear] WITH CHECK ADD CONSTRAINT [FK_ProgramYear_ClientProgram] FOREIGN KEY([ClientProgramId]) REFERENCES [dbo].[ClientProgram]([ClientProgramId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[MechanismTemplateElementScoring] DROP CONSTRAINT [FK_MechanismTemplateElementScoring_MechanismTemplateElement]; 	ALTER TABLE [dbo].[MechanismTemplateElementScoring] WITH CHECK ADD CONSTRAINT [FK_MechanismTemplateElementScoring_MechanismTemplateElement] FOREIGN KEY([MechanismTemplateElementId]) REFERENCES [dbo].[MechanismTemplateElement]([MechanismTemplateElementId]) ON DELETE CASCADE; 
ALTER TABLE [dbo].[ApplicationTemplateElement] DROP CONSTRAINT [FK_ApplicationTemplateElement_MechanismTemplateElement]; 	
