using System;

namespace Sra.P2rmis.WebModels.Setup
{
    /// <summary>
    /// Model for program data deliverable information
    /// </summary>
    public interface IProgramDeliverableModel
    {
        /// <summary>
        /// Gets or sets the client data deliverable identifier.
        /// </summary>
        /// <value>
        /// The client data deliverable identifier.
        /// </value>
        int ClientDataDeliverableId { get; set; }
        /// <summary>
        /// Gets or sets the name of the deliverable.
        /// </summary>
        /// <value>
        /// The name of the deliverable.
        /// </value>
        string DeliverableName { get; set; }
        /// <summary>
        /// Gets or sets the generated by.
        /// </summary>
        /// <value>
        /// The user's login name who generated the deliverable.
        /// </value>
        string GeneratedByName { get; set; }
        /// <summary>
        /// Gets or sets the generated date.
        /// </summary>
        /// <value>
        /// The generated date.
        /// </value>
        DateTime? GeneratedDate { get; set; }
        /// <summary>
        /// Gets or sets the program cycle deliverable identifier.
        /// </summary>
        /// <value>
        /// The program cycle deliverable identifier.
        /// </value>
        int? ProgramCycleDeliverableId { get; set; }
        /// <summary>
        /// Gets or sets the qc by.
        /// </summary>
        /// <value>
        /// The user's login name who qc'd the deliverable.
        /// </value>
        string QcByName { get; set; }
        /// <summary>
        /// Gets or sets the qc date.
        /// </summary>
        /// <value>
        /// The qc date.
        /// </value>
        DateTime? QcDate { get; set; }
        /// <summary>
        /// Gets or sets a value indicating whether [qc flag].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [qc flag]; otherwise, <c>false</c>.
        /// </value>
        bool? QcFlag { get; set; }
        /// <summary>
        /// Gets or sets the sort order.
        /// </summary>
        /// <value>
        /// The sort order.
        /// </value>
        int SortOrder { get; set; }
        /// <summary>
        /// Program year identifier.
        /// </summary>
        int ProgramYearId { get; set; }
        /// <summary>
        /// Receipt cycle.
        /// </summary>
        int ReceiptCycle { get; set; }
    }
}