SET IDENTITY_INSERT [dbo].[ClientSummaryTemplate] ON 

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (1, 19, N'Template_Summary_Statement_01_Standard', N'Template_Summary_Statement_01_Single_PI.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_01_Standard.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (2, 19, N'Template_Summary_Statement_02_Expedited', N'Template_Summary_Statement_02_Single_PI_Expedited.docx', N'uspSSData', 1, 1, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_02_Expedited.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (3, 19, N'Template_Summary_Statement_03_multiPI', N'Template_Summary_Statement_03_Multiple_PI.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_03_multiPI.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (4, 19, N'Template_Summary_Statement_04_multiPI_Expedited', N'Template_Summary_Statement_04_Multiple_PI_Expedited.docx', N'uspSSData', 1, 1, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_04_multiPI_Expedited.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (5, 19, N'Template_Summary_Statement_05_Blinded', N'Template_Summary_Statement_09_Blinded.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_05_Blinded.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (6, 19, N'Template_Summary_Statement_06_Online', N'Template_Summary_Statement_06_Online.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_06_Online.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (7, 19, N'Template_Summary_Statement_07_Online_Blinded', N'Template_Summary_Statement_07_Online_Blinded.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_07_Online_Blinded.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (8, 19, N'Template_Summary_Statement_08_Online_Blinded_Long', N'Template_Summary_Statement_07_Online_Blinded_Long.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_08_Online_Blinded_Long.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (9, 19, N'Template_Summary_Statement_09_Enthusiasm', N'Template_Summary_Statement_05_Single_PI_AdjO.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_09_Enthusiasm.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (10, 19, N'Template_Summary_Statement_10_MRDC_Extramural', N'Template_Summary_Statement_10_MRMC_Extramural.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_10_MRDC_Extramural.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (11, 19, N'Template_Summary_Statement_11_MRDC_Intramural', N'Template_Summary_Statement_11_MRMC_Intramural.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_11_MRDC_Intramural.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (12, 23, N'Template_Summary_Statement_12_MRDC_Intramural_CriteriaScore', N'Template_Summary_Statement_12_MRMC_Intramural_CriteriaS.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_12_MRDC_Intramural_CriteriaScore.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (13, 9, N'ACR_Discussed_SS_Template', N'template_cprit_resdiscussed.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/ACR_Discussed_SS_Template_20190116.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (14, 9, N'ACR_Not_Discussed_SS_Template', N'template_cprit_resnondiscussed.docx', N'uspSSDataNoCrAverage', 1, 1, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/ACR_Not_Discussed_SS_Template_20190116.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (16, 9, N'PDR_Discussed_SS_Template', N'template_cprit_productdev.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/PDR_Discussed_SS_Template_20190118.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (17, 9, N'PDR_Due_Diligence_SS_Template', N'template_cprit_duediligence.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/PDR_Due_Diligence_SS_Template_20190116.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (18, 9, N'PDR_Not_Discussed_SS_Template', N'template_cprit_productdev_nondiscussed.docx', N'uspSSData', 1, 1, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/PDR_Not_Discussed_SS_Template_20190118.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (19, 9, N'PRV_Discussed_SS_Template', N'template_cprit_prvdiscussed.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/PRV__Discussed_SS%20Template_20190117.doc?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (20, 9, N'PRV_DI_SS_Template', N'template_cprit_di.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/PRV_DI_SS%20Template_20190117.doc?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (21, 9, N'PRV_Not_Discussed_SS_Template', N'template_cprit_prvnondiscussed.docx', N'uspSSData', 1, 1, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/PRV_Not%20Discussed_SS%20Template_20190117.doc?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (22, 9, N'REC_Discussed_SS_Template', N'template_cprit_recdiscussed.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/REC_Discussed_SS_Template_20190118.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (24, 9, N'REC_Not_Discussed_SS_Template', N'template_cprit_recnondiscussed.docx', N'uspSSData', 1, 1, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/REC_Not_Discussed_SS_Template_20190118.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (26, 19, N'Template_Summary_Statement_01_Standard_OE', N'Template_Summary_Statement_01_Single_PI_OE.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_01_Standard.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (28, 19, N'Template_Summary_Statement_01_Standard_TopicCodes', N'Template_Summary_Statement_01_Single_PI_TopicCodes.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_01_Standard.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (29, 20, N'Template_Summary_Statement_01_Standard', N'Template_Summary_Statement_01_Single_PI_SOCOM.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_01_Standard.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (30, 20, N'Template_Summary_Statement_02_Expedited', N'Template_Summary_Statement_02_Single_PI_Expedited_SOCOM.docx', N'uspSSData', 1, 1, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_02_Expedited.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (31, 19, N'Template_Summary_Statement_02_Expedited_4Reviewers', N'Template_Summary_Statement_02_Single_PI_Expedited_4Reviewers.docx', N'uspSSData', 1, 1, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_02_Expedited.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (32, 19, N'Template_Summary_Statement_02_Expedited_TopicCodes', N'Template_Summary_Statement_02_Single_PI_Expedited_TopicCodes.docx', N'uspSSData', 1, 1, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_02_Expedited.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (33, 19, N'Template_Summary_Statement_03_multiPI_TopicCodes', N'Template_Summary_Statement_03_Multiple_PI_TopicCodes.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_03_multiPI.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (34, 19, N'Template_Summary_Statement_04_multiPI_Expedited_4Reviewers', N'Template_Summary_Statement_04_Multiple_PI_Expedited_4Reviewers.docx', N'uspSSData', 1, 1, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_04_multiPI_Expedited.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (35, 19, N'Template_Summary_Statement_06_Online_TopicArea', N'Template_Summary_Statement_06_Online_TopicArea.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_06_Online.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (36, 23, N'Template_Summary_Statement_11_MRDC_Intramural', N'Template_Summary_Statement_11_MRMC_Intramural.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_11_MRDC_Intramural.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (37, 23, N'Template_Summary_Statement_11_MRDC_Intramural_CCCRP', N'Template_Summary_Statement_11_MRMC_Intramural_CCCRP.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_11_MRDC_Intramural.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (38, 23, N'Template_Summary_Statement_11_MRDC_Intramural_MIDRP', N'Template_Summary_Statement_13_MIDRP_Intramural_Stdev.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_11_MRDC_Intramural.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (39, 23, N'Template_Summary_Statement_01_Standard', N'Template_Summary_Statement_01_Single_PI.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CDMRP-BRAES/CDMRP_OLD/DocCntrlLib/Template_Summary_Statement_01_Standard.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (40, 9, N'ACR_MIRA_Discussed_SS_Template', N'template_cpritres_mira_discussed.docx', N'uspSSData', 1, 0, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/ACR_Discussed_SS_Template_20190116.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (41, 9, N'ACR_MIRA_Not_Discussed_SS_Template', N'template_cpritres_mira_nondiscussed.docx', N'uspSSDataNoCrAverage', 1, 1, N'https://fuse.csra.com/civil/se/prsm/projects/CPRIT/03Resources/01-Summary%20Statement%20Templates/ACR_Not_Discussed_SS_Template_20190116.docx?Web=1')

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (42, 9, N'template_preeval', N'template_preeval.docx', N'uspSSData', 0, 0, NULL)

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (43, 19, N'template_baa_extramural', N'template_baa_extramural.docx', N'uspSSData', 0, 0, NULL)

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (44, 19, N'template_cdmrp_multiplepis', N'template_cdmrp_multiplepis.docx', N'uspSSData', 0, 0, NULL)

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (45, 19, N'template_cdmrp_standard', N'template_cdmrp_standard.docx', N'uspSSData', 0, 0, NULL)

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (46, 19, N'template_cdmrp_preeval', N'template_cdmrp_preeval.docx', N'uspSSData', 0, 0, NULL)

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (47, 19, N'template_cdmrp_nd', N'template_cdmrp_nd.docx', N'uspSSData', 0, 1, NULL)

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (48, 19, N'template_cdmrp_multiplepis_nd', N'template_cdmrp_multiplepis_nd.docx', N'uspSSData', 0, 1, NULL)

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (49, 19, N'template_NumericOE_blinded', N'template_NumericOE_blinded.docx', N'uspSSData', 0, 0, NULL)

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (50, 23, N'template_mrmc_intramural', N'template_mrmc_intramural.docx', N'uspSSData', 0, 0, NULL)

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (51, 23, N'template_baa_extramural', N'template_baa_extramural.docx', N'uspSSData', 0, 0, NULL)

INSERT [dbo].[ClientSummaryTemplate] ([ClientSummaryTemplateId], [ClientId], [TemplateName], [TemplateFileName], [StoredProcedureName], [ActiveFlag], [ExpeditedFlag], [PreviewLinkUrl]) VALUES (52, 23, N'template_cdmrp_standard', N'template_cdmrp_standard.docx', N'uspSSData', 0, 0, NULL)

SET IDENTITY_INSERT [dbo].[ClientSummaryTemplate] OFF