CREATE VIEW [dbo].[ViewMeetingRegistrationTravelFlight]
	AS SELECT [MeetingRegistrationTravelFlightId]
      ,[MeetingRegistrationTravelId]
      ,[CarrierName]
	  ,[FlightNumber]
	  ,[DepartureCity]
	  ,[DepartureDate]
	  ,[ArrivalCity]
	  ,[ArrivalDate]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[DeletedFlag]
      ,[DeletedBy]
      ,[DeletedDate]
  FROM [dbo].[MeetingRegistrationTravelFlight]
  WHERE DeletedFlag = 0