CREATE VIEW [dbo].[ViewMeetingRegistrationAttendance]
	AS SELECT [MeetingRegistrationAttendanceId]
      ,[MeetingRegistrationId]
      ,[AttendanceStartDate]
      ,[AttendanceEndDate]
      ,[MealRequestComments]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[DeletedFlag]
      ,[DeletedBy]
      ,[DeletedDate]
  FROM [dbo].[MeetingRegistrationAttendance]
  WHERE DeletedFlag = 0
