CREATE VIEW [dbo].ViewUser AS
SELECT [UserID]
      ,[UserLogin]
      ,[Password]
      ,[PasswordDate]
      ,[PasswordSalt]
      ,[Verified]
      ,[VerifiedDate]
      ,[IsActivated]
      ,[LastLoginDate]
      ,[IsLockedOut]
      ,[LastLockedOutDate]
      ,[NewPasswordRequested]
      ,[NewEmail]
      ,[NewEmailRequested]
      ,[PersonID]
      ,[CredentialSentBy]
      ,[CredentialSentDate]
	  ,[W9Verified]
	  ,[W9VerifiedDate]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[DeletedFlag]
      ,[DeletedBy]
      ,[DeletedDate]
  FROM [dbo].[User]
WHERE [DeletedFlag] = 0

