CREATE VIEW [dbo].[ViewMeetingRegistrationHotel]
	AS SELECT [MeetingRegistrationHotelId]
      ,[MeetingRegistrationId]
      ,[HotelNotRequiredFlag]
      ,[HotelId]
      ,[HotelCheckInDate]
      ,[HotelCheckOutDate]
      ,[HotelDoubleOccupancy]
      ,[HotelAndFoodRequestComments]
      ,[LegacyHousingId]
	  ,[CancellationFlag]
	  ,[CancellationDate]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[DeletedFlag]
      ,[DeletedBy]
      ,[DeletedDate]
  FROM [dbo].[MeetingRegistrationHotel]
  WHERE DeletedFlag = 0
