CREATE VIEW [dbo].[ViewProgramPayRate]
	AS SELECT [ProgramPayRateId]
      ,[ProgramYearId]
      ,[ClientParticipantTypeId]
	  ,[ParticipantMethodId]
      ,[RestrictedAssignedFlag]
	  ,[EmploymentCategoryId]
      ,[HonorariumAccepted]
	  ,[MeetingTypeId]
      ,[ConsultantFeeText]
      ,[ConsultantFee]
      ,[PeriodStartDate]
      ,[PeriodEndDate]
      ,[ManagerList]
      ,[DescriptionOfWork]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
  FROM [dbo].[ProgramPayRate]
  WHERE [DeletedFlag] = 0
