CREATE VIEW [dbo].[ViewSessionPayRate]
	AS SELECT [SessionPayRateId]
      ,[MeetingSessionId]
      ,[ClientParticipantTypeId]
	  ,[ParticipantMethodId]
      ,[RestrictedAssignedFlag]
	  ,[EmploymentCategoryId]
      ,[HonorariumAccepted]
      ,[ConsultantFeeText]
      ,[ConsultantFee]
      ,[PeriodStartDate]
      ,[PeriodEndDate]
      ,[ManagerList]
      ,[DescriptionOfWork]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
  FROM [dbo].[SessionPayRate]
  WHERE [DeletedFlag] = 0
