CREATE VIEW [dbo].[ViewSummaryReviewerDescription]
	AS SELECT [SummaryReviewerDescriptionId]
      ,[ProgramMechanismId]
      ,[ClientParticipantTypeId]
      ,[ClientRoleId]
      ,[AssignmentOrder]
      ,[CustomOrder]
      ,[DisplayName]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[DeletedFlag]
      ,[DeletedBy]
      ,[DeletedDate]
  FROM [dbo].[SummaryReviewerDescription]
  WHERE [DeletedFlag] = 0
