CREATE VIEW [dbo].[ViewMeetingRegistration]
	AS SELECT [MeetingRegistrationId]
      ,[PanelUserAssignmentId]
	  ,[SessionUserAssignmentId]
      ,[RegistrationSubmittedFlag]
      ,[RegistrationSubmittedDate]
      ,[LegacyMrId]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[DeletedFlag]
      ,[DeletedBy]
      ,[DeletedDate]
  FROM [dbo].[MeetingRegistration]
  WHERE DeletedFlag = 0
