CREATE VIEW [dbo].[ViewPanelUserRegistrationDocument]
	AS SELECT [PanelUserRegistrationDocumentId]
      ,[PanelUserRegistrationId]
      ,[ClientRegistrationDocumentId]
      ,[DocumentFile]
      ,[DateCompleted]
      ,[DateSigned]
	  ,[SignedOfflineFlag]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
  FROM [dbo].[PanelUserRegistrationDocument]
  WHERE DeletedFlag = 0
