CREATE VIEW [dbo].[ViewProgramMechanismSummaryStatement]
	AS SELECT [ProgramMechanismSummaryStatementId]
      ,[ProgramMechanismId]
      ,[ReviewStatusId]
      ,[TemplateLocation]
      ,[StoredProcedureName]
      ,[ClientSummaryTemplateId]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
      ,[DeletedFlag]
      ,[DeletedBy]
      ,[DeletedDate]
  FROM [dbo].[ProgramMechanismSummaryStatement]
  WHERE [DeletedFlag] = 0