SET IDENTITY_INSERT [ClientCoiType] ON

MERGE INTO [ClientCoiType] AS Target
USING (VALUES
  (1,19,'Investigator','Investigator (all active participants in the application)')
 ,(2,19,'Personal Relationship','Personal Relationship with the Investigator')
 ,(3,19,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(5,19,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(6,19,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(7,19,'Other','Other')
 ,(8,1,'Investigator','Investigator (all active participants in the application)')
 ,(9,1,'Personal Relationship','Personal Relationship with the Investigator')
 ,(10,1,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(11,1,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(12,1,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(13,1,'Other','Other')
 ,(14,2,'Other','Other')
 ,(15,2,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(16,2,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(17,2,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(18,2,'Personal Relationship','Personal Relationship with the Investigator')
 ,(19,2,'Investigator','Investigator (all active participants in the application)')
 ,(20,3,'Investigator','Investigator (all active participants in the application)')
 ,(21,3,'Personal Relationship','Personal Relationship with the Investigator')
 ,(22,3,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(23,3,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(24,3,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(25,3,'Other','Other')
 ,(26,4,'Other','Other')
 ,(27,4,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(28,4,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(29,4,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(30,4,'Personal Relationship','Personal Relationship with the Investigator')
 ,(31,4,'Investigator','Investigator (all active participants in the application)')
 ,(32,5,'Investigator','Investigator (all active participants in the application)')
 ,(33,5,'Personal Relationship','Personal Relationship with the Investigator')
 ,(34,5,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(35,5,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(36,5,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(37,5,'Other','Other')
 ,(38,6,'Other','Other')
 ,(39,6,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(40,6,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(41,6,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(42,6,'Personal Relationship','Personal Relationship with the Investigator')
 ,(43,6,'Investigator','Investigator (all active participants in the application)')
 ,(44,7,'Investigator','Investigator (all active participants in the application)')
 ,(45,7,'Personal Relationship','Personal Relationship with the Investigator')
 ,(46,7,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(47,7,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(48,7,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(49,7,'Other','Other')
 ,(50,8,'Other','Other')
 ,(51,8,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(52,8,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(53,8,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(54,8,'Personal Relationship','Personal Relationship with the Investigator')
 ,(55,8,'Investigator','Investigator (all active participants in the application)')
 ,(56,9,'Investigator','Investigator (all active participants in the application)')
 ,(57,9,'Personal Relationship','Personal Relationship with the Investigator')
 ,(58,9,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(59,9,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(60,9,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(61,9,'Other','Other')
 ,(62,10,'Other','Other')
 ,(63,10,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(64,10,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(65,10,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(66,10,'Personal Relationship','Personal Relationship with the Investigator')
 ,(67,10,'Investigator','Investigator (all active participants in the application)')
 ,(68,11,'Investigator','Investigator (all active participants in the application)')
 ,(69,11,'Personal Relationship','Personal Relationship with the Investigator')
 ,(70,11,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(71,11,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(72,11,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(73,11,'Other','Other')
 ,(74,12,'Other','Other')
 ,(75,12,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(76,12,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(77,12,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(78,12,'Personal Relationship','Personal Relationship with the Investigator')
 ,(79,12,'Investigator','Investigator (all active participants in the application)')
 ,(80,13,'Investigator','Investigator (all active participants in the application)')
 ,(81,13,'Personal Relationship','Personal Relationship with the Investigator')
 ,(82,13,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(83,13,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(84,13,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(85,13,'Other','Other')
 ,(86,14,'Other','Other')
 ,(87,14,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(88,14,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(89,14,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(90,14,'Personal Relationship','Personal Relationship with the Investigator')
 ,(91,14,'Investigator','Investigator (all active participants in the application)')
 ,(92,15,'Investigator','Investigator (all active participants in the application)')
 ,(93,15,'Personal Relationship','Personal Relationship with the Investigator')
 ,(94,15,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(95,15,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(96,15,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(97,15,'Other','Other')
 ,(98,16,'Other','Other')
 ,(99,16,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(100,16,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(101,16,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(102,16,'Personal Relationship','Personal Relationship with the Investigator')
 ,(103,16,'Investigator','Investigator (all active participants in the application)')
 ,(104,17,'Investigator','Investigator (all active participants in the application)')
 ,(105,17,'Personal Relationship','Personal Relationship with the Investigator')
 ,(106,17,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(107,17,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(108,17,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(109,17,'Other','Other')
 ,(110,18,'Other','Other')
 ,(111,18,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(112,18,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(113,18,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(114,18,'Personal Relationship','Personal Relationship with the Investigator')
 ,(115,18,'Investigator','Investigator (all active participants in the application)')
 ,(116,20,'Investigator','Investigator (all active participants in the application)')
 ,(117,20,'Personal Relationship','Personal Relationship with the Investigator')
 ,(118,20,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(119,20,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(120,20,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(121,20,'Other','Other')
 ,(122,21,'Other','Other')
 ,(123,21,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(124,21,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(125,21,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(126,21,'Personal Relationship','Personal Relationship with the Investigator')
 ,(127,21,'Investigator','Investigator (all active participants in the application)')
 ,(128,22,'Investigator','Investigator (all active participants in the application)')
 ,(129,22,'Personal Relationship','Personal Relationship with the Investigator')
 ,(130,22,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(131,22,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(132,22,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(133,22,'Other','Other')
 ,(134,23,'Investigator','Investigator (all active participants in the application)')
 ,(135,23,'Personal Relationship','Personal Relationship with the Investigator')
 ,(136,23,'Professional Relationship Investigator','Professional Relationship with the Investigator')
 ,(137,23,'Professional Relationship Institution','Professional Relationship with the Applicant''s Institution')
 ,(138,23,'Financial Interest','Personal Financial Interest in the Outcome of the Review')
 ,(139,23,'Other','Other')
) AS Source ([ClientCoiTypeId],[ClientId],[CoiTypeName],[CoiTypeDescription])
ON (Target.[ClientCoiTypeId] = Source.[ClientCoiTypeId])
WHEN MATCHED AND (
	NULLIF(Source.[ClientId], Target.[ClientId]) IS NOT NULL OR NULLIF(Target.[ClientId], Source.[ClientId]) IS NOT NULL OR 
	NULLIF(Source.[CoiTypeName], Target.[CoiTypeName]) IS NOT NULL OR NULLIF(Target.[CoiTypeName], Source.[CoiTypeName]) IS NOT NULL OR 
	NULLIF(Source.[CoiTypeDescription], Target.[CoiTypeDescription]) IS NOT NULL OR NULLIF(Target.[CoiTypeDescription], Source.[CoiTypeDescription]) IS NOT NULL) THEN
 UPDATE SET
  [ClientId] = Source.[ClientId], 
  [CoiTypeName] = Source.[CoiTypeName], 
  [CoiTypeDescription] = Source.[CoiTypeDescription]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([ClientCoiTypeId],[ClientId],[CoiTypeName],[CoiTypeDescription])
 VALUES(Source.[ClientCoiTypeId],Source.[ClientId],Source.[CoiTypeName],Source.[CoiTypeDescription])
;
GO
DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [ClientCoiType]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[ClientCoiType] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO

SET IDENTITY_INSERT [ClientCoiType] OFF
GO