using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Sra.P2rmis.WebModels.Setup;
using Sra.P2rmis.CrossCuttingServices;
namespace Sra.P2rmis.Web.UI.Models
{
    public class ProgramDataDeliverableViewModel
    {
        #region Constructor
        public ProgramDataDeliverableViewModel(IProgramDeliverableModel model)
        {
            DeliverableName = model.DeliverableName;
            GeneratedDate = model.GeneratedDate;
            GeneratedByName = model.GeneratedByName != null ? model.GeneratedByName.ToLower() : string.Empty;
            QcDate = model.QcDate;
            QcByName = model.QcByName != null ? model.QcByName.ToLower() : string.Empty;
            QcFlag = model.QcFlag ?? false;
            ClientDataDeliverableId = model.ClientDataDeliverableId;
            ProgramCycleDeliverableId = model.ProgramCycleDeliverableId;
            ProgramYearId = model.ProgramYearId;
            ReceiptCycle = model.ReceiptCycle;
        }
        #endregion
        #region Properties
        /// <summary>
        /// Gets or sets the name of the deliverable.
        /// </summary>
        /// <value>
        /// The name of the deliverable.
        /// </value>
        public string DeliverableName { get; set; }

        /// <summary>
        /// Gets or sets the generated date.
        /// </summary>
        /// <value>
        /// The deliverable generated date.
        /// </value>
        public DateTime? GeneratedDate { get; set; }

        /// <summary>
        /// Gets or sets the generated by.
        /// </summary>
        /// <value>
        /// The user's first name who generated the deliverable.
        /// </value>
        public string GeneratedByName { get; set; }

        /// <summary>
        /// Gets or sets the qc date.
        /// </summary>
        /// <value>
        /// The date the deliverable was QC'd.
        /// </value>
        public DateTime? QcDate { get; set; }

        /// <summary>
        /// Gets or sets the qc by.
        /// </summary>
        /// <value>
        /// The user's last name who qc'd the deliverable.
        /// </value>
        public string QcByName { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [qc flag].
        /// </summary>
        /// <value>
        ///   true if the deliverbale has been QC'd; otherwise, false.
        /// </value>
        public bool QcFlag { get; set; }

        /// <summary>
        /// Gets or sets the client data deliverable identifier.
        /// </summary>
        /// <value>
        /// The client data deliverable identifier.
        /// </value>
        public int ClientDataDeliverableId { get; set; }

        /// <summary>
        /// Gets or sets the program cycle deliverable identifier.
        /// </summary>
        /// <value>
        /// The program cycle deliverable identifier for a given deliverable instance.
        /// </value>
        public int? ProgramCycleDeliverableId { get; set; }
        /// <summary>
        /// Program year identifier.
        /// </summary>
        public int ProgramYearId { get; set; }
        /// <summary>
        /// Receipt cycle.
        /// </summary>
        public int ReceiptCycle { get; set; }
        #endregion
    }
}